// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Card } from "@/components/Card";\n'
  + 'import { Modal } from "@/components/Modal";\n'
  + '\n'
  + 'export default function Demo01() {\n'
  + '  const [isOpen, setIsOpen] = useState(false);\n'
  + '\n'
  + '  return (\n'
  + '    <>\n'
  + '      <Button onClick={() => setIsOpen(true)}>Open Modal</Button>\n'
  + '      <Modal isOpen={isOpen}>\n'
  + '        <Modal.Overlay onClick={() => setIsOpen(false)} />\n'
  + '        <Modal.Content yOffset="5dvh" shadow>\n'
  + '          <Card>\n'
  + '            <Card.Header>Modal Title</Card.Header>\n'
  + '            <Card.Content>\n'
  + '              This is a simple modal example using the Modal component from Copy\n'
  + '              UI.\n'
  + '            </Card.Content>\n'
  + '          </Card>\n'
  + '        </Modal.Content>\n'
  + '      </Modal>\n'
  + '    </>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
