// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Modal } from "@/components/Modal";\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo01() {\n'
  + '  const [isOpen, setIsOpen] = useState(false);\n'
  + '\n'
  + '  return (\n'
  + '    <>\n'
  + '      <Button onClick={() => setIsOpen(true)}>Open Modal</Button>\n'
  + '      <Modal isOpen={isOpen}>\n'
  + '        <Modal.Overlay onClick={() => setIsOpen(false)} />\n'
  + '        <Modal.Content>\n'
  + '          <Typography.Root>\n'
  + '            <Typography.H2>Modal Title</Typography.H2>\n'
  + '            <Typography.P>\n'
  + '              This is a simple modal example using the Modal component from Copy\n'
  + '              UI.\n'
  + '            </Typography.P>\n'
  + '          </Typography.Root>\n'
  + '        </Modal.Content>\n'
  + '      </Modal>\n'
  + '    </>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
