// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-28): Initial version.\n'
  + '- 0.1.1 (2025-09-29): Added controlled component support with `value` and\n'
  + "  `onChange` props. Add `size` prop with 'sm', 'md', 'lg' options.\n"
  + "- 0.1.2 (2025-10-02): Expand size options to include 'text', 'xs', 'xl'. Improve\n"
  + '  accessibility with proper button semantics, role="switch", and aria-checked.\n'
  + '  Use CSS custom properties for thumb gap positioning. Update size calculations\n'
  + '  to use 80% of input base heights for better proportions.\n'
  + '- 0.1.3 (2025-10-14): Add border styles, use ratio-based width calculation,\n'
  + '  adjust thumb gap values.\n'
  + '- 0.1.4 (2025-11-03): Use JSS & resolve-style for styles.\n'
  + '- 0.1.5 (2025-12-07): Refactor code and remove deprecated dependencies.\n'
  + '- 0.1.6 (2025-12-13): Update to support the new color scheme.\n'
  ;
