// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Switch } from "src/components/Switch";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <Switch />\n'
  + '  );\n'
  + '}\n'
  ;
