// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { Switch } from "src/components/Switch";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  const [checked, setChecked] = useState(false);\n'
  + '\n'
  + '  return (\n'
  + "    <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>\n"
  + '      <Switch size="sm" value={checked} onChange={setChecked} />\n'
  + '      <Switch size="md" value={checked} onChange={setChecked} />\n'
  + '      <Switch size="lg" value={checked} onChange={setChecked} />\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
