// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['Switch.tsx'] = ''
  + 'import { useState, type CSSProperties, type FC } from "react";\n'
  + '\n'
  + 'import { useTheme } from "../ThemeProvider";\n'
  + '\n'
  + 'import styles from "./Switch.module.scss";\n'
  + '\n'
  + 'export const Switch: FC = () => {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const [isChecked, setIsChecked] = useState(false);\n'
  + '\n'
  + '  const computedStyle = {\n'
  + "    '--switch-rail-width': '4rem',\n"
  + "    '--switch-rail-height': '2.25rem',\n"
  + "    '--switch-rail-bg': theme.colors.gray['300'],\n"
  + "    '--switch-rail-checked-bg': theme.colors.blue['600'],\n"
  + "    '--switch-thumb-bg': 'white',\n"
  + '  } as CSSProperties;\n'
  + '\n'
  + '  return (\n'
  + '    <div style={computedStyle} className={styles.rail} data-checked={isChecked} onClick={() => setIsChecked(!isChecked)}>\n'
  + '      <div className={styles.thumb} />\n'
  + '    </div>\n'
  + '  );\n'
  + '};\n'
  + '\n'
  + "Switch.displayName = 'Switch';\n"
  ;

sourceCode['Switch.module.scss'] = ''
  + '.rail {\n'
  + '  position: relative;\n'
  + '\n'
  + '  height: var(--switch-rail-height);\n'
  + '  width: var(--switch-rail-width);\n'
  + '  border-radius: 999999px;\n'
  + '  background-color: var(--switch-rail-bg);\n'
  + '\n'
  + '  cursor: pointer;\n'
  + '\n'
  + '  transition: background-color 0.15s;\n'
  + '\n'
  + '  &[data-checked="true"] {\n'
  + '    background-color: var(--switch-rail-checked-bg);\n'
  + '  }\n'
  + '}\n'
  + '\n'
  + '.thumb {\n'
  + '  position: absolute;\n'
  + '  top: 4px;\n'
  + '  left: 4px;\n'
  + '\n'
  + '  height: calc(var(--switch-rail-height) - 8px);\n'
  + '  width: calc(var(--switch-rail-height) - 8px);\n'
  + '  border-radius: 999999px;\n'
  + '  background-color: var(--switch-thumb-bg);\n'
  + '\n'
  + '  transition: left 0.15s;\n'
  + '\n'
  + '  .rail[data-checked="true"] & {\n'
  + '    left: calc(var(--switch-rail-width) - var(--switch-rail-height) + 4px);\n'
  + '  }\n'
  + '}\n'
  ;

sourceCode['index.ts'] = ''
  + 'export { Switch } from "./Switch";\n'
  ;

