// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['Switch.tsx'] = ''
  + 'import { type CSSProperties, type FC } from "react";\n'
  + 'import { merge } from "es-toolkit";\n'
  + '\n'
  + 'import { useTheme } from "../ThemeProvider";\n'
  + '\n'
  + 'import styles from "./Switch.module.scss";\n'
  + '\n'
  + 'export type SwitchProps = {\n'
  + "  size?: 'sm' | 'md' | 'lg';\n"
  + '  value: boolean;\n'
  + '  onChange?: (value: boolean) => void;\n'
  + '};\n'
  + '\n'
  + 'export const Switch: FC<SwitchProps> = (props) => {\n'
  + "  const { size = 'md', value, onChange } = props;\n"
  + '\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const computedStyle = mergeStyles([\n'
  + "    size === 'sm' && {\n"
  + "      '--switch-rail-width': '3.5rem',\n"
  + "      '--switch-rail-height': theme.tokens.inputBaseSmHeight,\n"
  + '    } as CSSProperties,\n'
  + "    size === 'md' && {\n"
  + "      '--switch-rail-width': '4rem',\n"
  + "      '--switch-rail-height': theme.tokens.inputBaseMdHeight,\n"
  + '    } as CSSProperties,\n'
  + "    size === 'lg' && {\n"
  + "      '--switch-rail-width': '4.5rem',\n"
  + "      '--switch-rail-height': theme.tokens.inputBaseLgHeight,\n"
  + '    } as CSSProperties,\n'
  + '    {\n'
  + "      '--switch-rail-bg': theme.colors.gray['300'],\n"
  + "      '--switch-rail-checked-bg': theme.colors.blue['600'],\n"
  + "      '--switch-thumb-bg': 'white',\n"
  + '    } as CSSProperties,\n'
  + '  ]);\n'
  + '\n'
  + '  return (\n'
  + '    <div\n'
  + '      style={computedStyle}\n'
  + '      className={styles.rail}\n'
  + '      data-checked={value}\n'
  + '      onClick={() => onChange?.(!value)}\n'
  + '    >\n'
  + '      <div className={styles.thumb} />\n'
  + '    </div>\n'
  + '  );\n'
  + '};\n'
  + '\n'
  + "Switch.displayName = 'Switch';\n"
  + '\n'
  + 'function mergeStyles(styles: (CSSProperties | false | undefined)[]) {\n'
  + '  return styles.reduce((prev, next) => {\n'
  + '    return next ? merge(prev as CSSProperties, next) : prev;\n'
  + '  }, {}) as CSSProperties;\n'
  + '}\n'
  ;

sourceCode['Switch.module.scss'] = ''
  + '.rail {\n'
  + '  position: relative;\n'
  + '\n'
  + '  height: var(--switch-rail-height);\n'
  + '  width: var(--switch-rail-width);\n'
  + '  border-radius: 999999px;\n'
  + '  background-color: var(--switch-rail-bg);\n'
  + '\n'
  + '  cursor: pointer;\n'
  + '\n'
  + '  transition: background-color 0.15s;\n'
  + '\n'
  + '  &[data-checked="true"] {\n'
  + '    background-color: var(--switch-rail-checked-bg);\n'
  + '  }\n'
  + '}\n'
  + '\n'
  + '.thumb {\n'
  + '  position: absolute;\n'
  + '  top: 4px;\n'
  + '  left: 4px;\n'
  + '\n'
  + '  height: calc(var(--switch-rail-height) - 8px);\n'
  + '  width: calc(var(--switch-rail-height) - 8px);\n'
  + '  border-radius: 999999px;\n'
  + '  background-color: var(--switch-thumb-bg);\n'
  + '\n'
  + '  transition: left 0.15s;\n'
  + '\n'
  + '  .rail[data-checked="true"] & {\n'
  + '    left: calc(var(--switch-rail-width) - var(--switch-rail-height) + 4px);\n'
  + '  }\n'
  + '}\n'
  ;

sourceCode['index.ts'] = ''
  + '// Switch from copy-ui @ 2025-09-29.\n'
  + '\n'
  + 'export { Switch } from "./Switch";\n'
  ;

