// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex gap="1rem" alignItems="center">\n'
  + '      <Button size="xs">Oh</Button>\n'
  + '      <Button size="sm" variant="filled">\n'
  + '        I mean\n'
  + '      </Button>\n'
  + '      <Button>Hello</Button>\n'
  + '      <Button size="lg" variant="filled" disabled>\n'
  + '        World\n'
  + '      </Button>\n'
  + '      <Button size="xl" variant="light">\n'
  + '        And you\n'
  + '      </Button>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
