// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex gap="1rem" alignItems="center">\n'
  + '      <Button variant="default">Default</Button>\n'
  + '      <Button variant="filled">Filled</Button>\n'
  + '      <Button variant="light">Light</Button>\n'
  + '      <Button variant="secondary">Secondary</Button>\n'
  + '      <Button variant="ghost">Ghost</Button>\n'
  + '      <Button variant="link">Link</Button>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
