// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex gap="1rem">\n'
  + '      <Button variant="filled" color="red">\n'
  + '        Delete item\n'
  + '      </Button>\n'
  + '      <Button variant="light" color="green">\n'
  + '        Save changes\n'
  + '      </Button>\n'
  + '      <Button variant="filled" color="yellow">\n'
  + '        Cancel\n'
  + '      </Button>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
