// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Button } from "@/components/Button";\n'
  + '\n'
  + 'export default function Example() {\n'
  + '  return (\n'
  + '    <Button variant="filled" color="red">\n'
  + '      Delete item\n'
  + '    </Button>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
