// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Star } from "lucide-react";\n'
  + '\n'
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Card } from "@/components/Card";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Card>\n'
  + '      <Card.Header>Designing Data-Intensive Application</Card.Header>\n'
  + '      <Card.Content>\n'
  + '        <Flex dir="column" gap="1rem">\n'
  + '          <Typography>\n'
  + '            <Typography.P>\n'
  + '              Designing Data-Intensive Applications is a book about the\n'
  + '              architecture of scalable and maintainable data systems.\n'
  + '            </Typography.P>\n'
  + '          </Typography>\n'
  + '          <Flex gap="0.5rem">\n'
  + '            <Button variant="filled" size="sm" leftSection={<Star />}>\n'
  + '              Add to favorites\n'
  + '            </Button>\n'
  + '            <Button variant="light" size="sm" color="red">\n'
  + '              Cancel\n'
  + '            </Button>\n'
  + '          </Flex>\n'
  + '        </Flex>\n'
  + '      </Card.Content>\n'
  + '    </Card>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
