// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Flex gap="1rem" alignItems="center">\n'
  + '        <Button variant="default">Default</Button>\n'
  + '        <Button variant="filled">Filled</Button>\n'
  + '        <Button variant="light">Light</Button>\n'
  + '        <Button variant="secondary">Secondary</Button>\n'
  + '        <Button variant="ghost">Ghost</Button>\n'
  + '        <Button variant="link">Link</Button>\n'
  + '      </Flex>\n'
  + '      <Flex gap="1rem" alignItems="center">\n'
  + '        <Button variant="default" disabled>\n'
  + '          Default\n'
  + '        </Button>\n'
  + '        <Button variant="filled" disabled>\n'
  + '          Filled\n'
  + '        </Button>\n'
  + '        <Button variant="light" disabled>\n'
  + '          Light\n'
  + '        </Button>\n'
  + '        <Button variant="secondary" disabled>\n'
  + '          Secondary\n'
  + '        </Button>\n'
  + '        <Button variant="ghost" disabled>\n'
  + '          Ghost\n'
  + '        </Button>\n'
  + '        <Button variant="link" disabled>\n'
  + '          Link\n'
  + '        </Button>\n'
  + '      </Flex>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
