// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Search, X } from "lucide-react";\n'
  + 'import { IbsBase } from "@/components/IbsBase";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <IbsBase size="md">\n'
  + '      <IbsBase.LeftSection>\n'
  + '        <Search size="1rem" />\n'
  + '      </IbsBase.LeftSection>\n'
  + '      <IbsBase.Wrapper>Content goes here</IbsBase.Wrapper>\n'
  + '      <IbsBase.RightSection>\n'
  + '        <X size="1rem" />\n'
  + '      </IbsBase.RightSection>\n'
  + '    </IbsBase>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
