[structure]
components = "src/components"
utils = "src/utils"

[generator]
class_helper = "classnames"

[components.CopyUiProvider]
with-mdx-provider = true
with-toast-provider = true

[components.Typography]
with-typography-codeblock = true

[components.Alert]

[components.AlertDialog]

[components.Avatar]

[components.Background]

[components.Breadcrumb]

[components.Button]

[components.ButtonGroup]

[components.Calendar]

[components.Card]

[components.Checkbox]

[components.CodeBlock]

[components.CodeHighlight]

[components.Combobox]

[components.DatePicker]

[components.Empty]

[components.Field]

[components.FileInput]

[components.Flex]

[components.Graph]

[components.IbsBase]

[components.IconButton]

[components.Input]

[components.Markdown]

[components.Modal]

[components.MultiSelect]

[components.Navbar]

[components.Paper]

[components.Popover]

[components.PopoverMenu]

[components.Resizable]

[components.ScrollArea]

[components.Select]

[components.SortIndicator]

[components.Spinner]

[components.Switch]

[components.Table]

[components.Tabs]

[components.Tag]

[components.Textarea]

[components.TimeSelector]

[components.Toast]

[components.Tooltip]

[components.Topbar]

[components.TreeSelect]

[utils.jss]

[utils.resolve-style2]
