// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode = ''
  + '/**\n'
  + ' * resolve-style2 from copy-ui @ 2025-11-23.\n'
  + ' *\n'
  + ' * The helper to calculate styles at runtime.\n'
  + ' */\n'
  + '\n'
  + 'import type { CSSProperties } from "react";\n'
  + '\n'
  + 'type Style = CSSProperties & Record<`--${string}`, string>;\n'
  + '\n'
  + 'type UnresolvedStyle = Record<string, Record<string, Style>>;\n'
  + '\n'
  + 'function resolveStyle2(style: UnresolvedStyle) {\n'
  + '  return (arg: Record<string, string>): CSSProperties => {\n'
  + '    const result = {};\n'
  + '\n'
  + '    for (const argVariant in arg) {\n'
  + '      const variantValue = arg[argVariant];\n'
  + '      const variantStyles = style[argVariant][variantValue];\n'
  + '      Object.assign(result, variantStyles);\n'
  + '    }\n'
  + '\n'
  + '    return result;\n'
  + '  };\n'
  + '}\n'
  + '\n'
  + 'export { resolveStyle2 };\n'
  ;

export default sourceCode;
