// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper radius="md" withBorder>\n'
  + '      This is a Paper component.\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
