// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Paper>This is a Paper component.</Paper>;\n'
  + '}\n'
  ;

export default demoSourceCode;
