// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useTheme } from "@/components/CopyUiProvider";\n'
  + 'import { Paper } from "@/components/Paper";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  return (\n'
  + '    <Paper style={{ backgroundColor: theme.colors.blue["000"] }}>\n'
  + '      <div>This is a raw Paper component.</div>\n'
  + '      <div>Without border.</div>\n'
  + '      <div>Without padding.</div>\n'
  + '      <div>And without shadow.</div>\n'
  + '      <div>Only has a background color.</div>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
