// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useId } from "react";\n'
  + '\n'
  + 'import { Checkbox } from "@/components/Checkbox";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo01() {\n'
  + '  const checkboxId = useId();\n'
  + '\n'
  + '  return (\n'
  + '    <Flex alignItems="center" gap="0.5rem">\n'
  + '      <Checkbox id={checkboxId} />\n'
  + '      <label htmlFor={checkboxId}>Hello World</label>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
