// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useId } from "react";\n'
  + '\n'
  + 'import { Checkbox } from "@/components/Checkbox";\n'
  + 'import { useJss, useMode, useTheme } from "@/components/CopyUiProvider";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo01() {\n'
  + '  const checkboxId = useId();\n'
  + '\n'
  + '  const mode = useMode();\n'
  + '  const jss = useJss();\n'
  + '  const theme = useTheme();\n'
  + '  const stx = jss.hash({\n'
  + '    color:\n'
  + '      mode === "light" ? theme.colors.gray["900"] : theme.colors.gray["100"],\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Flex alignItems="center" gap="0.5rem">\n'
  + '      <Checkbox id={checkboxId} />\n'
  + '      <label htmlFor={checkboxId} className={stx}>\n'
  + '        Hello World\n'
  + '      </label>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
