// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Avatar } from "src/components/Avatar";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="row" alignItems="center" gap="1rem">\n'
  + '      <Avatar color="blue" size="2.5rem" variant="circle">\n'
  + '        <Avatar.Img\n'
  + '          src="https://github.com/peterlitszo.png"\n'
  + '          alt="Peterlits Zo"\n'
  + '        />\n'
  + '      </Avatar>\n'
  + '      <Avatar color="blue" size="2.5rem" variant="rounded">\n'
  + '        <Avatar.Img\n'
  + '          src="https://github.com/peterlitszo.png"\n'
  + '          alt="Peterlits Zo"\n'
  + '        />\n'
  + '      </Avatar>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
