// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Avatar } from "src/components/Avatar";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Avatar size="2.5rem">\n'
  + '      <Avatar.Img src="https://github.com/peterlitszo.png" alt="Peterlits Zo" />\n'
  + '    </Avatar>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
