// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const changelog = ''
  + '- 2025-11-03: Initial version.\n'
  + '- 2025-11-23: Update the function `normalizeKey` to support CSS variable names\n'
  + '  better.\n'
  ;

export default changelog;
