// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-04: Initial version.\n'
  + '- 2025-09-05: Add the `size` prop.\n'
  ;
