// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-04): Initial version.\n'
  + '- 0.1.1 (2025-09-05): Add the `size` prop.\n'
  + '- 0.1.2 (2025-10-12): Code formatting improvement.\n'
  + '- 0.1.3 (2025-11-07): Support the new hook `useDirection` and remove the old\n'
  + '  hook. Let the `SortIndicator` has its style.\n'
  + '- 0.1.4 (2025-11-15): Add the variant `compact`. The `size` prop is removed --\n'
  + '  user should use CSS to set its size.\n'
  + '- 0.1.5 (2025-12-17): Add the new hook `useDirections`, which is useful to\n'
  + '  manage multiple sort indicators.\n'
  ;
