export const demoSourceCode = ''
  + 'import { useContext } from "react";\n'
  + 'import { Button } from "src/components/Button";\n'
  + '\n'
  + 'import { SortIndicator, useSortIndicatorState } from "src/components/SortIndicator";\n'
  + 'import { ThemeContext } from "src/components/ThemeProvider";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  const theme = useContext(ThemeContext);\n'
  + "  const { direction, handleClick } = useSortIndicatorState('asc');\n"
  + '\n'
  + '  return (\n'
  + '    <Button\n'
  + '      rightSection={\n'
  + '        <SortIndicator\n'
  + "          style={{ color: theme.colors.gray['600'] }}\n"
  + '          size="1rem"\n'
  + '          direction={direction}\n'
  + '        />\n'
  + '      }\n'
  + '      onClick={handleClick}\n'
  + '    >\n'
  + '      <span>Volume</span>\n'
  + '    </Button>\n'
  + '  );\n'
  + '}\n'
  ;
