// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-20): Initial version.\n'
  + '- 0.1.1 (2025-09-23): Add support for pausing the auto-dismiss timer when\n'
  + '  hovering over a toast & add basic styles.\n'
  + '- 0.1.2 (2025-10-05): Code formatting improvement.\n'
  + '- 0.1.3 (2025-10-28): Use `Modal.Raw` to render the toast container.\n'
  + '- 0.1.4 (2025-11-19): Remove the dependency on `ThemeProvider`.\n'
  + '- 0.1.5 (2025-11-28): Enhance this with more toast types and optional\n'
  + '  description.\n'
  + '- 0.1.6 (2025-12-13): Update to support the new color scheme.\n'
  ;
