// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-20: Initial version.\n'
  + '- 2025-09-23: Add support for pausing the auto-dismiss timer when hovering\n'
  + '  over a toast & add basic styles.\n'
  + '- 2025-10-05: Code formatting improvement.\n'
  + '- 2025-10-28: Use `Modal.Raw` to render the toast container.\n'
  + '- 2025-11-19: Remove the dependency on `ThemeProvider`.\n'
  ;
