// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { useToast } from "src/components/Toast";\n'
  + 'import { Button } from "src/components/Button";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  const { addToast } = useToast();\n'
  + '  const [counter, setCounter] = useState(1);\n'
  + '\n'
  + '  const handleAddToast = () => {\n'
  + '    addToast(`Toast message ${counter}`);\n'
  + '    setCounter(counter + 1);\n'
  + '  };\n'
  + '\n'
  + '  return (\n'
  + "    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>\n"
  + '      <Button onClick={handleAddToast}>\n'
  + '        Add Toast\n'
  + '      </Button>\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
