// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { Button } from "@/components/Button";\n'
  + 'import { useToast } from "@/components/Toast";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  const { addToast } = useToast();\n'
  + '  const [counter, setCounter] = useState(1);\n'
  + '\n'
  + '  const handleAddToast = () => {\n'
  + '    addToast(`Toast message ${counter}`);\n'
  + '    setCounter(counter + 1);\n'
  + '  };\n'
  + '\n'
  + '  return <Button onClick={handleAddToast}>Add Toast</Button>;\n'
  + '}\n'
  ;
