export const sourceCode: Record<string, string> = {};

sourceCode['index.ts'] = ''
  + '// Toast from copy-ui @ 2025-09-20\n'
  + '\n'
  + 'export { Toast, useToast } from "./Toast";\n'
  ;

sourceCode['Toast.module.scss'] = ''
  + '.toastContainer {\n'
  + '  position: fixed;\n'
  + '  bottom: 1rem;\n'
  + '  right: 1rem;\n'
  + '}\n'
  + '\n'
  + '.toastList {\n'
  + '  display: flex;\n'
  + '  flex-direction: column;\n'
  + '  gap: 0.5rem;\n'
  + '}\n'
  + '\n'
  + '.toast {\n'
  + '  background-color: var(--toast-bg-color);\n'
  + '  padding: 0.5rem 1rem;\n'
  + '  border-radius: 0.25rem;\n'
  + '  border-width: 1px;\n'
  + '  border-style: solid;\n'
  + '  border-color: var(--toast-border-color);\n'
  + '}\n'
  ;

sourceCode['Toast.tsx'] = ''
  + 'import { createContext, useContext, type FC, type PropsWithChildren } from "react";\n'
  + 'import { useStore } from "zustand";\n'
  + 'import { createStore, type StoreApi } from "zustand";\n'
  + '\n'
  + "import styles from './Toast.module.scss';\n"
  + 'import { useTheme } from "../ThemeProvider";\n'
  + '\n'
  + '// ToastStore\n'
  + '// =============================================================================\n'
  + '\n'
  + 'type ToastStoreState = {\n'
  + '  toasts: Array<string>;\n'
  + '};\n'
  + '\n'
  + 'type ToastStoreActions = {\n'
  + '  addToast: (message: string) => void;\n'
  + '};\n'
  + '\n'
  + 'type ToastStore = ToastStoreState & ToastStoreActions;\n'
  + '\n'
  + 'function buildToastStore() {\n'
  + '  return createStore<ToastStore>()((set) => ({\n'
  + '    toasts: [],\n'
  + '    \n'
  + '    addToast: (message) => {\n'
  + '      setTimeout(() => {\n'
  + '        set((state) => ({\n'
  + '          toasts: state.toasts.slice(1),\n'
  + '        }))\n'
  + '      }, 3000);\n'
  + '\n'
  + '      set((state) => ({\n'
  + '        toasts: [...state.toasts, message],\n'
  + '      }))\n'
  + '    },\n'
  + '  }));\n'
  + '}\n'
  + '\n'
  + '// ToastContext\n'
  + '// =============================================================================\n'
  + '\n'
  + 'const ToastContext = createContext<StoreApi<ToastStore> | null>(null);\n'
  + '\n'
  + 'const ToastContextWrapper: FC<PropsWithChildren> = ({ children }) => {\n'
  + '  const store = buildToastStore();\n'
  + '\n'
  + '  return (\n'
  + '    <ToastContext value={store}>\n'
  + '      {children}\n'
  + '    </ToastContext>\n'
  + '  );\n'
  + '}\n'
  + '\n'
  + "ToastContextWrapper.displayName = 'Toast.Context';\n"
  + '\n'
  + '// ToastContainer\n'
  + '// =============================================================================\n'
  + '\n'
  + 'const ToastContainer: FC = () => {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const store = useContext(ToastContext);\n'
  + '  if (!store) {\n'
  + "    throw new Error('Toast.Container must be used within a Toast.Context');\n"
  + '  };\n'
  + '\n'
  + '  const toasts = useStore(store, (state) => state.toasts);\n'
  + '\n'
  + '  const computedStyle = {\n'
  + "    '--toast-bg-color': 'white',\n"
  + "    '--toast-border-color': theme.colors.gray['300'],\n"
  + '  } as React.CSSProperties;\n'
  + '\n'
  + '  return (\n'
  + '    <section\n'
  + '      style={computedStyle}\n'
  + '      className={styles.toastContainer}\n'
  + '    >\n'
  + '      <ul className={styles.toastList}>\n'
  + '        {toasts.map((toast, index) => (\n'
  + '          <li key={index} className={styles.toast}>\n'
  + '            {toast}\n'
  + '          </li>\n'
  + '        ))}\n'
  + '      </ul>\n'
  + '    </section>\n'
  + '  );\n'
  + '};\n'
  + '\n'
  + "ToastContainer.displayName = 'Toast.Container';\n"
  + '\n'
  + '// useToast\n'
  + '// =============================================================================\n'
  + '\n'
  + 'export function useToast() {\n'
  + '  const store = useContext(ToastContext);\n'
  + '  if (!store) {\n'
  + "    throw new Error('useToast must be used within a Toast.Context');\n"
  + '  };\n'
  + '\n'
  + '  return {\n'
  + '    addToast: store.getState().addToast,\n'
  + '  };\n'
  + '}\n'
  + '\n'
  + '// Toast\n'
  + '// =============================================================================\n'
  + '\n'
  + 'type ToastComponent = {\n'
  + '  Container: typeof ToastContainer;\n'
  + '  Context: typeof ToastContextWrapper;\n'
  + '}\n'
  + '\n'
  + 'export const Toast: ToastComponent = () => {};\n'
  + '\n'
  + 'Toast.Container = ToastContainer;\n'
  + 'Toast.Context = ToastContextWrapper;\n'
  ;

