// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper withBorder withPadding radius="md" style={{ width: "40rem" }}>\n'
  + '      <Typography>\n'
  + '        <Typography.Ul>\n'
  + '          <Typography.Li>\n'
  + '            2025-10-02: Initial version (with{" "}\n'
  + '            <Typography.Code>Typography.H1</Typography.Code> component).\n'
  + '          </Typography.Li>\n'
  + '          <Typography.Li>\n'
  + '            2025-10-03: Added <Typography.Code>Typography.H2</Typography.Code>,{" "}\n'
  + '            <Typography.Code>Typography.H3</Typography.Code> and{" "}\n'
  + '            <Typography.Code>Typography.P</Typography.Code>\n'
  + '            components. Support the <Typography.Code>mt</Typography.Code> prop\n'
  + '            for margin-top spacing & update CSS styles to make it look better.\n'
  + '          </Typography.Li>\n'
  + '          <Typography.Li>\n'
  + '            2025-10-04: Add <Typography.Code>Typography.H4</Typography.Code>{" "}\n'
  + '            component. Support <Typography.Code>mb</Typography.Code> prop for\n'
  + '            margin-bottom spacing. Increase{" "}\n'
  + '            <Typography.Code>H1</Typography.Code> font size and improve prop\n'
  + '            handling consistency.\n'
  + '          </Typography.Li>\n'
  + '        </Typography.Ul>\n'
  + '      </Typography>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
