// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { Typography as Ty, Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper withBorder withPadding radius="md" style={{ width: "40rem" }}>\n'
  + '      <Typography>\n'
  + '        <Ty.Ul>\n'
  + '          <Ty.Li>\n'
  + '            2025-10-02: Initial version (with <Ty.Code>Typography.H1</Ty.Code>{" "}\n'
  + '            component).\n'
  + '          </Ty.Li>\n'
  + '          <Ty.Li>\n'
  + '            2025-10-03: Added <Ty.Code>Typography.H2</Ty.Code>,{" "}\n'
  + '            <Ty.Code>Typography.H3</Ty.Code> and <Ty.Code>Typography.P</Ty.Code>\n'
  + '            components. Support the <Ty.Code>mt</Ty.Code> prop for margin-top\n'
  + '            spacing & update CSS styles to make it look better.\n'
  + '          </Ty.Li>\n'
  + '          <Ty.Li>\n'
  + '            2025-10-04: Add <Ty.Code>Typography.H4</Ty.Code> component. Support{" "}\n'
  + '            <Ty.Code>mb</Ty.Code> prop for margin-bottom spacing. Increase{" "}\n'
  + '            <Ty.Code>H1</Ty.Code> font size and improve prop handling\n'
  + '            consistency.\n'
  + '          </Ty.Li>\n'
  + '        </Ty.Ul>\n'
  + '      </Typography>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
