// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper withBorder withPadding radius="md" style={{ width: "40rem" }}>\n'
  + '      <Typography>\n'
  + '        <Typography.P>\n'
  + '          This is the main source code repository for Rust. It contains the\n'
  + '          compiler, standard library, and documentation.\n'
  + '        </Typography.P>\n'
  + '        <Typography.H2>Why Rust</Typography.H2>\n'
  + '        <Typography.Ol>\n'
  + '          <Typography.Li>\n'
  + '            <Typography.Strong>Performance:</Typography.Strong> Fast and\n'
  + '            memory-efficient, suitable for critical services, embedded devices,\n'
  + '            and easily integrated with{" "}\n'
  + '            <Typography.Em>other languages</Typography.Em>.\n'
  + '          </Typography.Li>\n'
  + '          <Typography.Li>\n'
  + '            <Typography.Em>etc.</Typography.Em>\n'
  + '          </Typography.Li>\n'
  + '        </Typography.Ol>\n'
  + '      </Typography>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
