// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { Typography as Ty, Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper withBorder withPadding radius="md" style={{ width: "40rem" }}>\n'
  + '      <Typography>\n'
  + '        <Ty.H1>React (software)</Ty.H1>\n'
  + '        <Ty.P>\n'
  + '          React (also known as React.js or ReactJS) is a free and open-source\n'
  + '          front-end JavaScript library that aims to make building user\n'
  + '          interfaces based on components more "seamless".\n'
  + '        </Ty.P>\n'
  + '        <Ty.P>\n'
  + '          React can be used to develop single-page, mobile, or server-rendered\n'
  + '          applications with frameworks like Next.js and React Router. Because\n'
  + '          React is only concerned with the user interface and rendering\n'
  + '          components to the DOM, React applications often rely on libraries for\n'
  + '          routing and other client-side functionality.\n'
  + '        </Ty.P>\n'
  + '        <Ty.H2>Notable features</Ty.H2>\n'
  + '        <Ty.H3>Declarative</Ty.H3>\n'
  + '        <Ty.P>\n'
  + '          React adheres to the declarative programming paradigm. Developers\n'
  + '          design views for each state of an application, and React updates and\n'
  + '          renders components when data changes. This is in contrast with\n'
  + '          imperative programming.\n'
  + '        </Ty.P>\n'
  + '        <Ty.H3>Components</Ty.H3>\n'
  + '        <Ty.P>\n'
  + '          React code is made of entities called components. These components are\n'
  + '          modular and can be reused. React applications typically consist of\n'
  + '          many layers of components. The components are rendered to a root\n'
  + '          element in the DOM using the React DOM library.\n'
  + '        </Ty.P>\n'
  + '      </Typography>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
