// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { Typography as Ty, Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper withBorder withPadding radius="md" style={{ width: "40rem" }}>\n'
  + '      <Typography>\n'
  + '        <Ty.P>\n'
  + '          This is the main source code repository for{" "}\n'
  + '          <Ty.A href="https://www.rust-lang.org/">Rust</Ty.A>. It contains the\n'
  + '          compiler, standard library, and documentation.\n'
  + '        </Ty.P>\n'
  + '        <Ty.H2>Why Rust</Ty.H2>\n'
  + '        <Ty.Ol>\n'
  + '          <Ty.Li>\n'
  + '            <Ty.Strong>Performance:</Ty.Strong> Fast and memory-efficient,\n'
  + '            suitable for critical services, embedded devices, and easily\n'
  + '            integrated with <Ty.Em>other languages</Ty.Em>.\n'
  + '          </Ty.Li>\n'
  + '          <Ty.Li>\n'
  + '            <Ty.Em>etc.</Ty.Em>\n'
  + '          </Ty.Li>\n'
  + '        </Ty.Ol>\n'
  + '      </Typography>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
