// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-05: Initial version.\n'
  + '- 2025-10-16: Adjust its styles - improve spacing and hover states.\n'
  ;
