// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-05): Initial version.\n'
  + '- 0.1.1 (2025-10-16): Adjust its styles - improve spacing and hover states.\n'
  + '- 0.1.2 (2025-10-31): Support the `enclosed` variant.\n'
  + '- 0.1.3 (2025-11-15): Adjust spacing between tabs for better visual balance.\n'
  + '  Remove the dependency on deprecated `ThemeProvider` and use `CopyUiProvider`\n'
  + '  instead.\n'
  + '- 0.1.4 (2025-12-07): Support the `size` prop.\n'
  + '- 0.1.5 (2025-12-13): Update to support the new color scheme.\n'
  ;
