// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { SortIndicator, useDirection } from "@/components/SortIndicator";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const [direction, setDirection] = useDirection("asc");\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Button\n'
  + '        rightSection={<SortIndicator variant="default" direction={direction} />}\n'
  + '        onClick={() => setDirection()}\n'
  + '      >\n'
  + '        <span>Volume</span>\n'
  + '      </Button>\n'
  + '      <Button\n'
  + '        rightSection={<SortIndicator variant="compact" direction={direction} />}\n'
  + '        onClick={() => setDirection()}\n'
  + '      >\n'
  + '        <span>Volume</span>\n'
  + '      </Button>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
