// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { SortIndicator, useDirection } from "@/components/SortIndicator";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const [direction, setDirection] = useDirection("asc");\n'
  + '\n'
  + '  return (\n'
  + '    <Button\n'
  + '      rightSection={<SortIndicator direction={direction} />}\n'
  + '      onClick={() => setDirection()}\n'
  + '    >\n'
  + '      <span>Volume</span>\n'
  + '    </Button>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
