// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-11-15): Initial version.\n'
  + '- 0.1.1 (2025-11-23): Support the dark mode.\n'
  + '- 0.1.2 (2025-11-25): Update the `padding-block` style for `Table.Cell`.\n'
  ;
