// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-11: Initial version.\n'
  + '- 2025-09-13: Enhance Input component with more styling variables (\n'
  + '  `--input-font-size`, `--input-line-height`, `--input-caret-color`,\n'
  + '  `--input-placeholder-color`).\n'
  + '- 2025-09-22: Support the `size` props (`sm`, `md`, `lg`) for Input component to\n'
  + '  adjust height and font size. Etc.\n'
  + '- 2025-09-26: Use theme tokens for Input component styles.\n'
  + '- 2025-09-30: Use `InputBase` as a wrapper for the Input component.\n'
  + '- 2025-10-05: Support the `leftSection` and `rightSection` props for Input\n'
  + '  component to add elements inside the input field on the left or right side.\n'
  + '  Adjust padding based on presence of these sections.\n'
  + '- 2025-10-20: Support `disabled` prop.\n'
  + '- 2025-10-26: Support `variant` prop. Update styles to make it look better.\n'
  + '- 2025-11-19: Remove the dependency on `ThemeProvider`.\n'
  + '- 2025-11-20: Support the `width` prop and let `className` and `style` props\n'
  + '  effect the `InputBase` component rather than the internal `input` element.\n'
  + '- 2025-12-07: Use `IbsBase` component instead of `InputBase` component.\n'
  + '- 2025-12-18: Use `useOptionalFieldContext` hook to get the field context for\n'
  + "  the `id` prop's default value. Support `status` prop to set the error state.\n"
  + '- 2026-02-13: Use `IbsBaseStyleProps` in `InputProps` to avoid DOM event type\n'
  + '  pollution from `IbsBase` root props.\n'
  ;
