// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-11): Initial version.\n'
  + '- 0.1.1 (2025-09-13): Enhance Input component with more styling variables (\n'
  + '  `--input-font-size`, `--input-line-height`, `--input-caret-color`,\n'
  + '  `--input-placeholder-color`).\n'
  + '- 0.1.2 (2025-09-22): Support the `size` props (`sm`, `md`, `lg`) for Input\n'
  + '  component to adjust height and font size. Etc.\n'
  + '- 0.1.3 (2025-09-26): Use theme tokens for Input component styles.\n'
  + '- 0.1.4 (2025-09-30): Use `InputBase` as a wrapper for the Input component.\n'
  + '- 0.1.5 (2025-10-05): Support the `leftSection` and `rightSection` props for\n'
  + '  Input component to add elements inside the input field on the left or right\n'
  + '  side. Adjust padding based on presence of these sections.\n'
  + '- 0.1.6 (2025-10-20): Support `disabled` prop.\n'
  + '- 0.1.7 (2025-10-26): Support `variant` prop. Update styles to make it look\n'
  + '  better.\n'
  + '- 0.1.8 (2025-11-19): Remove the dependency on `ThemeProvider`.\n'
  + '- 0.1.9 (2025-11-20): Support the `width` prop and let `className` and `style`\n'
  + '  props effect the `InputBase` component rather than the internal `input`\n'
  + '  element.\n'
  + '- 0.1.10 (2025-12-07): Use `IbsBase` component instead of `InputBase` component.\n'
  + '- 0.1.11 (2025-12-18): Use `useOptionalFieldContext` hook to get the field\n'
  + "  context for the `id` prop's default value. Support `status` prop to set the\n"
  + '  error state.\n'
  + '- 0.1.12 (2026-02-13): Use `IbsBaseStyleProps` in `InputProps` to avoid DOM\n'
  + '  event type pollution from `IbsBase` root props.\n'
  ;
