export const demoSourceCode = ''
  + 'import { Input } from "src/components/Input";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <Input\n'
  + '      placeholder="Type something..."\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;
