// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Input } from "src/components/Input";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + "    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>\n"
  + '      <Input size="sm" placeholder="Type something..." />\n'
  + '      <Input placeholder="Type something..." />\n'
  + '      <Input size="lg" placeholder="Type something..." />\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
