// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Search } from "lucide-react";\n'
  + 'import { Input } from "src/components/Input";\n'
  + 'import { useTheme } from "@/components/ThemeProvider";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  return (\n'
  + '    <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>\n'
  + '      <Input\n'
  + '        leftSection={<Search color={theme.colors.gray["600"]} size="60%" />}\n'
  + '        size="sm"\n'
  + '        placeholder="Search..."\n'
  + '      />\n'
  + '      <Input placeholder="Type something..." />\n'
  + '      <Input rightSection={<span>$</span>} size="lg" placeholder="1,000,000" />\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
