// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['index.ts'] = ''
  + '// Input from copy-ui @ 2025-09-30.\n'
  + '\n'
  + "export { Input } from './Input';\n"
  + "export type { InputProps } from './Input';\n"
  ;

sourceCode['Input.tsx'] = ''
  + 'import classNames from "classnames";\n'
  + 'import { merge } from "es-toolkit";\n'
  + 'import { type ComponentProps, type CSSProperties, type FC } from "react";\n'
  + '\n'
  + 'import { useTheme } from "../ThemeProvider";\n'
  + 'import { InputBase } from "../InputBase";\n'
  + '\n'
  + 'import styles from "./Input.module.scss";\n'
  + '\n'
  + "export type InputProps = Omit<ComponentProps<'input'>, 'size'> & {\n"
  + "  size?: 'sm' | 'md' | 'lg';\n"
  + '};\n'
  + '\n'
  + 'export const Input: FC<InputProps> = (props) => {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + "  const { size = 'md', className, style, ...rest } = props;\n"
  + '\n'
  + '  const computedStyle = mergeStyles([\n'
  + "    size === 'sm' && {\n"
  + "      '--input-font-size': theme.tokens.inputBaseSmFontSize,\n"
  + "      '--input-line-height': theme.tokens.inputBaseSmLineHeight,\n"
  + '    } as CSSProperties,\n'
  + "    size === 'md' && {\n"
  + "      '--input-font-size': theme.tokens.inputBaseMdFontSize,\n"
  + "      '--input-line-height': theme.tokens.inputBaseMdLineHeight,\n"
  + '    } as CSSProperties,\n'
  + "    size === 'lg' && {\n"
  + "      '--input-font-size': theme.tokens.inputBaseLgFontSize,\n"
  + "      '--input-line-height': theme.tokens.inputBaseLgLineHeight,\n"
  + '    } as CSSProperties,\n'
  + '    {\n'
  + "      '--input-padding-inline': '0.5rem',\n"
  + "      '--input-border-color-focus': theme.colors.blue['800'],\n"
  + "      '--input-placeholder-color': theme.tokens.inputBasePlaceholderColor,\n"
  + "      '--input-caret-color': theme.colors.blue['600'],\n"
  + '    } as CSSProperties,\n'
  + '    style,\n'
  + '  ]);\n'
  + '\n'
  + '  return (\n'
  + '    <InputBase size={size}>\n'
  + '      <input\n'
  + '        className={classNames(className, styles.input)}\n'
  + '        style={computedStyle}\n'
  + '        {...rest}\n'
  + '      />\n'
  + '    </InputBase>\n'
  + '  );\n'
  + '}\n'
  + '\n'
  + "Input.displayName = 'Input';\n"
  + '\n'
  + 'function mergeStyles(styles: (CSSProperties | false | undefined)[]) {\n'
  + '  return styles.reduce((prev, next) => {\n'
  + '    return next ? merge(prev as CSSProperties, next) : prev;\n'
  + '  }, {}) as CSSProperties;\n'
  + '}\n'
  ;

sourceCode['Input.module.scss'] = ''
  + '.input {\n'
  + '  flex: 1;\n'
  + '\n'
  + '  padding-inline: var(--input-padding-inline);\n'
  + '  font-size: var(--input-font-size);\n'
  + '  line-height: var(--input-line-height);\n'
  + '  caret-color: var(--input-caret-color);\n'
  + '  background-color: white;\n'
  + '\n'
  + '  &:focus {\n'
  + '    outline: none;\n'
  + '    border-color: var(--input-border-color-focus);\n'
  + '  }\n'
  + '\n'
  + '  &::placeholder {\n'
  + '    color: var(--input-placeholder-color);\n'
  + '  }\n'
  + '}\n'
  ;

