// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Textarea } from "@/components/Textarea";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Textarea />;\n'
  + '}\n'
  ;

export default demoSourceCode;
