// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-10): Initial version.\n'
  + '- 0.1.1 (2025-11-05): Support the `size` prop.\n'
  + '- 0.1.2 (2025-12-07): Support the `icon` prop.\n'
  ;
