// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['Spinner.module.scss'] = ''
  + '@layer components {\n'
  + '  .spinner {\n'
  + '    width: 1rem;\n'
  + '    height: 1rem;\n'
  + '    animation: spin 1s linear infinite;\n'
  + '  }\n'
  + '\n'
  + '  @keyframes spin {\n'
  + '    from {\n'
  + '      transform: rotate(0deg);\n'
  + '    }\n'
  + '    to {\n'
  + '      transform: rotate(360deg);\n'
  + '    }\n'
  + '  }\n'
  + '}\n'
  ;

sourceCode['index.ts'] = ''
  + '// Spinner from copy-ui @ 2025-10-10.\n'
  + '\n'
  + 'export { Spinner } from "./Spinner";\n'
  ;

sourceCode['Spinner.tsx'] = ''
  + 'import classNames from "classnames";\n'
  + 'import { Loader2Icon } from "lucide-react";\n'
  + 'import type { FC } from "react";\n'
  + '\n'
  + 'import styles from "./Spinner.module.scss";\n'
  + '\n'
  + 'type SpinnerProps = React.ComponentProps<"svg">;\n'
  + '\n'
  + 'export const Spinner: FC<SpinnerProps> = (props) => {\n'
  + '  const { className, ...rest } = props;\n'
  + '\n'
  + '  return (\n'
  + '    <Loader2Icon\n'
  + '      role="status"\n'
  + '      aria-label="Loading"\n'
  + '      className={classNames(styles.spinner, className)}\n'
  + '      {...rest}\n'
  + '    />\n'
  + '  );\n'
  + '};\n'
  + '\n'
  + 'Spinner.displayName = "Spinner";\n'
  ;

