// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Spinner } from "@/components/Spinner";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Spinner />;\n'
  + '}\n'
  ;

export default demoSourceCode;
