// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Baby, Loader2Icon, LoaderIcon, LoaderPinwheel } from "lucide-react";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Spinner } from "@/components/Spinner";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="row" gap="2rem" alignItems="center">\n'
  + '      <Spinner size="1.5rem" icon={LoaderIcon} />\n'
  + '      <Spinner size="1.5rem" icon={Loader2Icon} />\n'
  + '      <Spinner size="1.5rem" icon={LoaderPinwheel} />\n'
  + '      <Spinner size="1.5rem" icon={Baby} />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
