// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Spinner } from "@/components/Spinner";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="row" gap="2rem" alignItems="center">\n'
  + '      <Spinner size="0.75rem" />\n'
  + '      <Spinner size="1rem" />\n'
  + '      <Spinner size="1.25rem" />\n'
  + '      <Spinner size="1.5rem" />\n'
  + '      <Spinner size="1.75rem" />\n'
  + '      <Spinner size="2rem" />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
