// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Tag } from "src/components/Tag";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Tag>Copy UI</Tag>;\n'
  + '}\n'
  ;

export default demoSourceCode;
