// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Select } from "@/components/Select";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Select options={[]} />;\n'
  + '}\n'
  ;

export default demoSourceCode;
