// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Field } from "@/components/Field";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Field>\n'
  + '      <Field.Label>My Favorite Fruit</Field.Label>\n'
  + '      <Field.Input type="text" placeholder="Enter fruit name" />\n'
  + '      <Field.Error>Sorry that is not my favorite fruit.</Field.Error>\n'
  + '    </Field>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
