// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Field } from "@/components/Field";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Field>\n'
  + '        <Field.Label>Username</Field.Label>\n'
  + '        <Input width="sm" type="text" placeholder="Enter your username" />\n'
  + '      </Field>\n'
  + '\n'
  + '      <Field>\n'
  + '        <Field.Label>Email</Field.Label>\n'
  + '        <Input type="email" placeholder="Enter your email" />\n'
  + "        <Field.Description>We'll never share your email.</Field.Description>\n"
  + '      </Field>\n'
  + '\n'
  + '      <Field>\n'
  + '        <Field.Label>Country</Field.Label>\n'
  + '        <Field.Select\n'
  + '          options={[\n'
  + '            { value: "ca", label: "Canada" },\n'
  + '            { value: "cn", label: "China" },\n'
  + '            { value: "uk", label: "United Kingdom" },\n'
  + '            { value: "us", label: "United States" },\n'
  + '          ]}\n'
  + '        />\n'
  + '      </Field>\n'
  + '\n'
  + '      <Field>\n'
  + '        <Field.Label>About You</Field.Label>\n'
  + '        <Field.Textarea placeholder="Tell us about yourself" />\n'
  + '      </Field>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
