// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Field } from "@/components/Field";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Field>\n'
  + '      <Field.Label>My Favorite Fruit</Field.Label>\n'
  + '      <Input status="error" type="text" placeholder="Enter fruit name" />\n'
  + '      <Field.Error>Sorry that is not my favorite fruit.</Field.Error>\n'
  + '    </Field>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
