// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { AlertCircle } from "lucide-react";\n'
  + 'import { Alert } from "@/components/Alert";\n'
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const stx = jss.hash({\n'
  + '    width: "30rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Alert color="red" className={stx}>\n'
  + '      <AlertCircle size="1.25rem" />\n'
  + '      <Alert.Title>Foobar</Alert.Title>\n'
  + '      <Alert.Description>Some description.</Alert.Description>\n'
  + '    </Alert>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
