// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Info } from "lucide-react";\n'
  + 'import { Alert } from "@/components/Alert";\n'
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const stx = jss.hash({\n'
  + '    width: "30rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Alert color="blue" className={stx}>\n'
  + '      <Info size="1.25rem" />\n'
  + '      <Alert.Title>See Also</Alert.Title>\n'
  + '      <Alert.Description>\n'
  + '        You can also check the CodeBlock component - it is built on top of\n'
  + '        CodeHighlight, but with more features (copy button, scroll area, etc.).\n'
  + '      </Alert.Description>\n'
  + '    </Alert>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
