// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Card } from "@/components/Card";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Card>\n'
  + '      <Card.Header>This is the Card Header</Card.Header>\n'
  + '      <Card.Content>\n'
  + '        This is a Card component with some content inside.\n'
  + '      </Card.Content>\n'
  + '    </Card>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
