// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Card } from "@/components/Card";\n'
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const footerStx = jss.hash({\n'
  + '    display: "flex",\n'
  + '    justifyContent: "flex-end",\n'
  + '    gap: "0.5rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Card width="20rem">\n'
  + '      <Card.Header>This is the Card Header</Card.Header>\n'
  + '      <Card.Content>\n'
  + '        This is a Card component with some content inside. You can write\n'
  + '        anything you want here.\n'
  + '      </Card.Content>\n'
  + '      <Card.Footer className={footerStx}>\n'
  + '        <Button variant="light" size="sm">\n'
  + '          Confirm\n'
  + '        </Button>\n'
  + '        <Button variant="secondary" size="sm">\n'
  + '          Cancel\n'
  + '        </Button>\n'
  + '      </Card.Footer>\n'
  + '    </Card>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
