// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Card } from "@/components/Card";\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Card width="30rem">\n'
  + '      <Card.Content withTypography>\n'
  + '        <Typography.P>\n'
  + '          This Card component demonstrates the use of Typography components\n'
  + '          within Card.Content. When the{" "}\n'
  + '          <Typography.Code>withTypography</Typography.Code> prop is enabled, all\n'
  + '          content is automatically wrapped in a Typography container.\n'
  + '        </Typography.P>\n'
  + '        <Typography.H2>Features</Typography.H2>\n'
  + '        <Typography.H3>Automatic Typography Wrapping</Typography.H3>\n'
  + '        <Typography.P>\n'
  + '          The <Typography.Code>withTypography</Typography.Code> prop ensures\n'
  + '          consistent typography styling across all content within the Card.\n'
  + '        </Typography.P>\n'
  + '        <Typography.H3>Rich Content Support</Typography.H3>\n'
  + '        <Typography.P>\n'
  + '          You can use various Typography components like headings, paragraphs,\n'
  + '          and inline code to create rich, structured content.\n'
  + '        </Typography.P>\n'
  + '      </Card.Content>\n'
  + '    </Card>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
