// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Search } from "lucide-react";\n'
  + '\n'
  + 'import { useTheme } from "@/components/CopyUiProvider";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Input\n'
  + '        leftSection={<Search color={theme.colors.gray["600"]} size="50%" />}\n'
  + '        placeholder="Search..."\n'
  + '      />\n'
  + '      <Input rightSection={<span>$</span>} size="lg" placeholder="1,000,000" />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
