// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Input variant="filled" placeholder="Search..." />;\n'
  + '}\n'
  ;

export default demoSourceCode;
