// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Input size="sm" placeholder="Type something..." />\n'
  + '      <Input size="md" placeholder="Type something..." />\n'
  + '      <Input size="lg" placeholder="Type something..." />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
