// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const stx = jss.hash({\n'
  + '    width: "30rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem" className={stx}>\n'
  + '      <Input w="12rem" placeholder="Type something..." />\n'
  + '      <Input w="16rem" placeholder="Type something..." />\n'
  + '      <Input w="20rem" placeholder="Type something..." />\n'
  + '      <Input w="100%" placeholder="Type something..." />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
