// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Input disabled placeholder="Disabled input" />\n'
  + '      <Input disabled variant="filled" placeholder="Disabled filled input" />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
