// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <Input size="xs" w="20rem" placeholder="Type something..." />\n'
  + '      <Input size="sm" w="20rem" placeholder="Type something..." />\n'
  + '      <Input size="md" w="20rem" placeholder="Type something..." />\n'
  + '      <Input size="lg" w="20rem" placeholder="Type something..." />\n'
  + '      <Input size="xl" w="20rem" placeholder="Type something..." />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
