// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Plus, Search } from "lucide-react";\n'
  + '\n'
  + 'import { Avatar } from "@/components/Avatar";\n'
  + 'import { useTheme } from "@/components/CopyUiProvider";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { IconButton } from "@/components/IconButton";\n'
  + 'import { Input } from "@/components/Input";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  return (\n'
  + '    <Flex gap="1rem">\n'
  + '      <Input\n'
  + '        w="16rem"\n'
  + '        variant="filled"\n'
  + '        placeholder="Search your todos..."\n'
  + '        rightSection={<Search size="50%" color={theme.colors.gray["600"]} />}\n'
  + '      />\n'
  + '      <IconButton>\n'
  + '        <Plus />\n'
  + '      </IconButton>\n'
  + '      <Avatar size="2.125rem">\n'
  + '        <Avatar.Img src="https://github.com/peterlitszo.png" />\n'
  + '        <Avatar.Fallback>S</Avatar.Fallback>\n'
  + '      </Avatar>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
