// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Card } from "@/components/Card";\n'
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const flexStx = jss.hash({\n'
  + '    width: "40rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Flex direction="row" gap="1rem" className={flexStx}>\n'
  + '      <Card>\n'
  + '        <Card.Content>Card 1</Card.Content>\n'
  + '      </Card>\n'
  + '      <Card>\n'
  + '        <Card.Content>Card 2</Card.Content>\n'
  + '      </Card>\n'
  + '      <Card>\n'
  + '        <Card.Content>Card 3</Card.Content>\n'
  + '      </Card>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
