// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Card } from "@/components/Card";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="row" gap="1rem" style={{ width: "40rem" }}>\n'
  + '      <Card>\n'
  + '        <Card.Content>Card 1</Card.Content>\n'
  + '      </Card>\n'
  + '      <Card>\n'
  + '        <Card.Content>Card 2</Card.Content>\n'
  + '      </Card>\n'
  + '      <Card>\n'
  + '        <Card.Content>Card 3</Card.Content>\n'
  + '      </Card>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
