// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Inbox } from "lucide-react";\n'
  + 'import { Button } from "@/components/Button";\n'
  + 'import { Empty } from "@/components/Empty";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Empty>\n'
  + '      <Empty.Header>\n'
  + '        <Empty.Media>\n'
  + '          <Inbox />\n'
  + '        </Empty.Media>\n'
  + '        <Empty.Title>No Projects Found</Empty.Title>\n'
  + '        <Empty.Description>\n'
  + '          Try adjusting your search criteria or create a new project.\n'
  + '        </Empty.Description>\n'
  + '      </Empty.Header>\n'
  + '      <Empty.ContentFlex gap="0.5rem">\n'
  + '        <Button variant="filled" size="sm">\n'
  + '          Create Project\n'
  + '        </Button>\n'
  + '        <Button variant="light" size="sm">\n'
  + '          Import Projects\n'
  + '        </Button>\n'
  + '      </Empty.ContentFlex>\n'
  + '    </Empty>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
