// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-18): Initial version.\n'
  + '- 0.1.1 (2025-10-26): Support `size` prop and custom separator content.\n'
  + '- 0.1.2 (2025-11-24): Support dark mode.\n'
  ;
