// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-18: Initial version.\n'
  + '- 2025-10-26: Support `size` prop and custom separator content.\n'
  ;
