// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-26: Initial version.\n'
  + '- 2025-10-08: Add alpha transparency, code formatting improvements.\n'
  ;
