// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-26): Initial version.\n'
  + '- 0.1.1 (2025-10-08): Add alpha transparency, code formatting improvements.\n'
  + '- 0.1.2 (2025-10-21): Support `withDot` and `size` props.\n'
  + '- 0.1.3 (2025-11-20): Support more variants.\n'
  + '- 0.1.4 (2025-12-13): Update to support the new color scheme.\n'
  ;
