// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Tag } from "src/components/Tag";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + "    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>\n"
  + "      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>\n"
  + '        <Tag>React</Tag>\n'
  + '        <Tag>TypeScript</Tag>\n'
  + '        <Tag>JavaScript</Tag>\n'
  + '        <Tag>CSS</Tag>\n'
  + '        <Tag>HTML</Tag>\n'
  + '      </div>\n'
  + '      \n'
  + "      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>\n"
  + '        <Tag color="red">Frontend</Tag>\n'
  + '        <Tag color="green">Backend</Tag>\n'
  + '        <Tag color="yellow">Full Stack</Tag>\n'
  + '      </div>\n'
  + '      \n'
  + "      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap' }}>\n"
  + '        <Tag height="1rem">New</Tag>\n'
  + '        <Tag height="1.25rem">Popular</Tag>\n'
  + '        <Tag height="1.5rem">Featured</Tag>\n'
  + '        <Tag height="1.75rem">Recommended</Tag>\n'
  + '      </div>\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
