// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + '// Tag from copy-ui @ 2025-09-26.\n'
  + '\n'
  + 'export { Tag } from "./Tag";\n'
  ;

sourceCode['Tag.tsx'] = ''
  + 'import type { CSSProperties, FC } from "react";\n'
  + '\n'
  + 'import styles from "./Tag.module.scss";\n'
  + 'import { useTheme } from "../ThemeProvider";\n'
  + '\n'
  + 'interface TagProps {\n'
  + '  children: React.ReactNode;\n'
  + '\n'
  + '  color?: string;\n'
  + '  height?: string;\n'
  + '}\n'
  + '\n'
  + 'export const Tag: FC<TagProps> = (props) => {\n'
  + '  const {\n'
  + '    children,\n'
  + "    color = 'blue',\n"
  + "    height = '1.5rem',\n"
  + '  } = props;\n'
  + '\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const computedStyles = {\n'
  + "    '--tag-bg-color': theme.colors[color]['000'],\n"
  + "    '--tag-color': theme.colors[color]['900'],\n"
  + "    '--tag-height': height,\n"
  + '  } as CSSProperties;\n'
  + '\n'
  + '  return (\n'
  + '    <div className={styles.tag} style={computedStyles}>\n'
  + '      {children}\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;

sourceCode['Tag.module.scss'] = ''
  + '.tag {\n'
  + '  display: inline-flex;\n'
  + '  align-items: center;\n'
  + '  justify-content: center;\n'
  + '\n'
  + '  height: var(--tag-height);\n'
  + '  font-size: calc(var(--tag-height) * 0.625);\n'
  + '  padding-inline: calc(var(--tag-height) * 0.375);\n'
  + '  border-radius: 999999px;\n'
  + '\n'
  + '  background-color: var(--tag-bg-color);\n'
  + '  color: var(--tag-color);\n'
  + '}\n'
  ;

