// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-25: Initial version.\n'
  + '- 2025-11-28: Support `date` and `onDateChange` props to make the component\n'
  + '  controllable.\n'
  + '- 2025-12-12: Use `IbsBase` rather than deprecated `InputBase` component.\n'
  + '- 2026-02-13: Use `IbsBaseRootProps` instead of `ComponentProps<typeof\n'
  + '  IbsBase>` for a clearer root/style contract.\n'
  + '- 2026-02-14: Replace interactive `span` with `button` and remove\n'
  + '  `biome-ignore` for a11y lint rules.\n'
  ;
