// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-25): Initial version.\n'
  + '- 0.1.1 (2025-11-28): Support `date` and `onDateChange` props to make the\n'
  + '  component controllable.\n'
  + '- 0.1.2 (2025-12-12): Use `IbsBase` rather than deprecated `InputBase`\n'
  + '  component.\n'
  + '- 0.1.3 (2026-02-13): Use `IbsBaseRootProps` instead of `ComponentProps<typeof\n'
  + '  IbsBase>` for a clearer root/style contract.\n'
  + '- 0.1.4 (2026-02-14): Replace interactive `span` with `button` and remove\n'
  + '  `biome-ignore` for a11y lint rules.\n'
  ;
