// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { DatePicker } from "@/components/DatePicker";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="row" gap="1rem" alignItems="center">\n'
  + '      <DatePicker />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
