// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-02): Initial version.\n'
  + '- 0.1.1 (2025-10-04): Support custom `style` prop and spread additional props.\n'
  + '  Extend from `ComponentProps<"div">` for better TypeScript support.\n'
  + '- 0.1.2 (2025-10-26): Refactor to use `useJss` for styling.\n'
  + '- 0.1.3 (2025-11-19): Make `Flex` support `direction`, `items` and `justify`\n'
  + '  prop as alias of `dir`, `alignItems` and `justifyContent`. Support `start` and\n'
  + '  `end` values for `justify` prop. Support append class by `className` prop.\n'
  ;
