// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-02: Initial version.\n'
  + '- 2025-10-04: Support custom `style` prop and spread additional props. Extend\n'
  + '  from `ComponentProps<"div">` for better TypeScript support.\n'
  ;
