// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-24: Initial version.\n'
  + '- 2025-10-25: Use `useRef` to avoid re-creating zustand store on each render.\n'
  + '- 2025-10-27: Wrap children with `Toast.Context`.\n'
  ;
