// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-24: Initial version.\n'
  + '- 2025-10-25: Use `useRef` to avoid re-creating zustand store on each render.\n'
  + '- 2025-10-27: Wrap children with `Toast.Context`.\n'
  + '- 2025-11-04: Move the original `ThemeProvider` into `CopyUiProvider` and\n'
  + '  support the `useTheme`, etc. The `ThemeProvider` now is deprecated.\n'
  + '- 2025-11-06: Export the `useTheme` hook. And remove the `style` tag built for\n'
  + '  SSR after hydration in `CopyUiProvider`.\n'
  + '- 2025-11-08: Add simple MDX support for `CopyUiProvider`.\n'
  + '- 2025-11-15: Export the `ColorName` and `ColorNo` types. Add colors cyan, teal,\n'
  + '  lime and orange to the theme.\n'
  + '- 2025-11-17: Export type `Theme`. And Enhance internal MdxProvider to use more\n'
  + '  sub-components of `Typography`.\n'
  ;
