// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-09): Initial version.\n'
  + '- 0.1.1 (2025-10-12): Support the `className` prop.\n'
  + '- 0.1.2 (2025-11-03): Support the `title` prop. Rename the `height` prop to\n'
  + '  `scrollAreaHeight`, and rename the `maxHeight` prop to `scrollAreaMaxHeight`.\n'
  + '- 0.1.3 (2025-12-08): Add `withCopyButton` prop. Now support to copy the code to\n'
  + '  clipboard by clicking the copy button.\n'
  ;
