// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-09: Initial version.\n'
  + '- 2025-10-12: Support the `className` prop.\n'
  ;
