// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-13): Initial version.\n'
  + '- 0.1.1 (2025-10-14): Make `Modal.Content` support `center` and `shadow` props.\n'
  + '  Update `Modal.Content` styles.\n'
  + '- 0.1.2 (2025-10-27): Add `Modal.Raw` component.\n'
  + '- 0.1.3 (2025-11-23): Remove the dependency on `ThemeProvider`. Support\n'
  + '  `yOffset` prop for `Modal.Content`.\n'
  ;
