// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-11-06): Initial version.\n'
  + '- 0.1.1 (2025-12-16): Use `IbsBase` as the base component, etc.\n'
  + '- 0.1.2 (2026-02-13): Use `IbsBaseRootProps` in `MultiSelect` and trigger\n'
  + '  context types instead of `ComponentProps<typeof IbsBase>`.\n'
  ;
