// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const componentsRoutes: { name: string, path: string }[] = [
  {"name": "Avatar", "path": "routes/components/Avatar/index.tsx"},
  {"name": "Button", "path": "routes/components/Button/index.tsx"},
  {"name": "ButtonGroup", "path": "routes/components/ButtonGroup/index.tsx"},
  {"name": "CodeHighlight", "path": "routes/components/CodeHighlight/index.tsx"},
  {"name": "DatePicker", "path": "routes/components/DatePicker/index.tsx"},
  {"name": "IconButton", "path": "routes/components/IconButton/index.tsx"},
  {"name": "Input", "path": "routes/components/Input/index.tsx"},
  {"name": "Popover", "path": "routes/components/Popover/index.tsx"},
  {"name": "Select", "path": "routes/components/Select/index.tsx"},
  {"name": "SortIndicator", "path": "routes/components/SortIndicator/index.tsx"},
  {"name": "ThemeProvider", "path": "routes/components/ThemeProvider/index.tsx"},
  {"name": "TimeSelector", "path": "routes/components/TimeSelector/index.tsx"},
  {"name": "Toast", "path": "routes/components/Toast/index.tsx"},
  {"name": "Tooltip", "path": "routes/components/Tooltip/index.tsx"},
];
