// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const utilsRoutes: { name: string, path: string }[] = [
  {"name": "resolve-style", "path": "routes/utils/resolve-style/index.tsx"},
];
