// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { CodeBlock } from "@/components/CodeBlock/code-block";\n'
  + '\n'
  + 'import code from "./code.txt?raw";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <CodeBlock\n'
  + '      code={code}\n'
  + '      lang="typescript"\n'
  + '      scrollAreaMaxHeight="15rem"\n'
  + '      withLineNumbers\n'
  + '      withCopyButton\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;
sourceCode['code.txt'] = ''
  + 'import { Loader2Icon } from "lucide-react"\n'
  + '\n'
  + 'import { cn } from "@/lib/utils"\n'
  + '\n'
  + 'function Spinner({ className, ...props }: React.ComponentProps<"svg">) {\n'
  + '  return (\n'
  + '    <Loader2Icon\n'
  + '      role="status"\n'
  + '      aria-label="Loading"\n'
  + '      className={cn("size-4 animate-spin", className)}\n'
  + '      {...props}\n'
  + '    />\n'
  + '  )\n'
  + '}\n'
  + '\n'
  + 'export { Spinner }\n'
  ;
;

export default sourceCode;
