// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-08: Initial version.\n'
  + '- 2025-09-11: Support the prop `onClickOutside` of `Popover.Portal`.\n'
  + '  Refactor it to make it simpler with zustand. Use `autoUpdate` from\n'
  + '  `@floating-ui/react` to handle the position update automatically. etc.\n'
  + '- 2025-09-22: Add support for disabling the trigger click handler when clicking\n'
  + '  outside the portal but clicking the trigger as well.\n'
  + '- 2025-09-25: Add `placement` prop to `Popover` to control the placement of the\n'
  + '  portal.\n'
  + "- 2025-09-25: Support `onOpen` and `onClose` props for `Popover.Trigger`'s\n"
  + '  render. And rename its `onClick` props to `onToggle`.\n'
  + '- 2025-10-03: Fix missing dependencies in useEffect hooks.\n'
  + '- 2025-10-26: Using `Modal` component in `Popover.Portal` to handle the portal\n'
  + '  rendering.\n'
  + "- 2025-10-27: Make `Popover.Trigger`'s render can have prop `isOpen`.\n"
  + '- 2025-10-28: Using `Modal.Raw` rather than `Modal`. Export the type\n'
  + '  `PopoverTriggerRender`.\n'
  + '- 2025-11-15: Add `offset` prop to `Popover` to control the distance between the\n'
  + '  trigger and the portal.\n'
  ;
