// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-08): Initial version.\n'
  + '- 0.1.1 (2025-09-11): Support the prop `onClickOutside` of `Popover.Portal`.\n'
  + '  Refactor it to make it simpler with zustand. Use `autoUpdate` from\n'
  + '  `@floating-ui/react` to handle the position update automatically. etc.\n'
  + '- 0.1.2 (2025-09-22): Add support for disabling the trigger click handler when\n'
  + '  clicking outside the portal but clicking the trigger as well.\n'
  + '- 0.1.3 (2025-09-25): Add `placement` prop to `Popover` to control the placement\n'
  + '  of the portal.\n'
  + '- 0.1.4 (2025-09-25): Support `onOpen` and `onClose` props for\n'
  + "  `Popover.Trigger`'s render. And rename its `onClick` props to `onToggle`.\n"
  + '- 0.1.5 (2025-10-03): Fix missing dependencies in useEffect hooks.\n'
  + '- 0.1.6 (2025-10-26): Using `Modal` component in `Popover.Portal` to handle the\n'
  + '  portal rendering.\n'
  + "- 0.1.7 (2025-10-27): Make `Popover.Trigger`'s render can have prop `isOpen`.\n"
  + '- 0.1.8 (2025-10-28): Using `Modal.Raw` rather than `Modal`. Export the type\n'
  + '  `PopoverTriggerRender`.\n'
  + '- 0.1.9 (2025-11-15): Add `offset` prop to `Popover` to control the distance\n'
  + '  between the trigger and the portal.\n'
  + '- 0.1.10 (2025-11-26): Support `anchor="pointer"` to make the popover follow the\n'
  + '  mouse cursor.\n'
  + '- 0.1.11 (2025-11-28): Use `useClickOutside` hook from `CopyUiProvider` to\n'
  + '  handle the click outside event -- make nested popover components work\n'
  + '  correctly.\n'
  + '- 0.1.12 (2025-12-14): Add `openDelay` prop to `Popover.Trigger` to control the\n'
  + '  delay time before the popover is opened.\n'
  ;
