export const demoSourceCode = ''
  + 'import { Button } from "src/components/Button";\n'
  + 'import { Popover } from "src/components/Popover";\n'
  + '\n'
  + 'import styles from "./Demo.module.scss";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <Popover>\n'
  + '      <Popover.Trigger\n'
  + '        render={({ setRef, onClick }) => (\n'
  + '          <Button ref={(el) => setRef(el)} onClick={onClick}>Open</Button>\n'
  + '        )}\n'
  + '      />\n'
  + '      <Popover.Portal\n'
  + '        onClickOutside={({ closePortal: close }) => close()}\n'
  + '        render={({ setRef, isOpen, floatingStyles }) => (\n'
  + '          isOpen && (\n'
  + '            <div\n'
  + '              ref={(el) => setRef(el)}\n'
  + '              style={floatingStyles}\n'
  + '              className={styles.popoverPortal}\n'
  + '            >\n'
  + '              You click to open me!\n'
  + '            </div>\n'
  + '          )\n'
  + '        )}\n'
  + '      />\n'
  + '    </Popover>\n'
  + '  );\n'
  + '}\n'
  ;
