export const sourceCode: Record<string, string> = {};

sourceCode['Popover.tsx'] = ''
  + 'import { autoUpdate, flip, offset, useFloating } from "@floating-ui/react";\n'
  + 'import {\n'
  + '  createContext, memo, useContext, useEffect, useMemo, useState,\n'
  + '  type CSSProperties, type FC, type MouseEventHandler, type ReactNode,\n'
  + '} from "react";\n'
  + 'import { createPortal } from "react-dom";\n'
  + 'import { createStore, useStore, type StoreApi } from "zustand";\n'
  + '\n'
  + '// PopoverStore\n'
  + '// =============================================================================\n'
  + '\n'
  + 'type PopoverStoreState = {\n'
  + '  isOpen: boolean;\n'
  + '\n'
  + '  floatingStyles: CSSProperties;\n'
  + '  elRef: Element | null;\n'
  + '  floatingRef: HTMLElement | null;\n'
  + '\n'
  + '  triggerClickHandlerEnabled: boolean;\n'
  + '}\n'
  + '\n'
  + 'type PopoverStoreActions = {\n'
  + '  toggle: () => void;\n'
  + '  close: () => void;\n'
  + '\n'
  + '  setFloatingStyles: (floatingStyles: CSSProperties) => void;\n'
  + '  setElRef: (el: Element | null) => void;\n'
  + '  setFloatingRef: (el: HTMLElement | null) => void;\n'
  + '\n'
  + '  disableTriggerClickHandler: () => void;\n'
  + '  enableTriggerClickHandler: () => void;\n'
  + '}\n'
  + '\n'
  + 'type PopoverStore = PopoverStoreState & PopoverStoreActions;\n'
  + '\n'
  + 'type BuildPopoverStoreArgs = {\n'
  + '  onSetElRef: (el: Element | null) => void;\n'
  + '  onSetFloatingRef: (el: HTMLElement | null) => void;\n'
  + '}\n'
  + '\n'
  + 'function buildPopoverStore(args: BuildPopoverStoreArgs) {\n'
  + '  return createStore<PopoverStore>()((set) => ({\n'
  + '    isOpen: false,\n'
  + '    floatingStyles: {},\n'
  + '    elRef: null,\n'
  + '    floatingRef: null,\n'
  + '    triggerClickHandlerEnabled: true,\n'
  + '\n'
  + '    toggle: () => set((state) => ({ isOpen: !state.isOpen })),\n'
  + '    close: () => set(() => ({ isOpen: false })),\n'
  + '    setFloatingStyles: (floatingStyles) => set(() => ({ floatingStyles })),\n'
  + '    setElRef: (el) => set(() => {\n'
  + '      args.onSetElRef(el);\n'
  + '      return { elRef: el };\n'
  + '    }),\n'
  + '    setFloatingRef: (el) => set(() => {\n'
  + '      args.onSetFloatingRef(el);\n'
  + '      return { floatingRef: el };\n'
  + '    }),\n'
  + '    disableTriggerClickHandler: () => set(() => ({\n'
  + '      triggerClickHandlerEnabled: false\n'
  + '    })),\n'
  + '    enableTriggerClickHandler: () => set(() => ({\n'
  + '      triggerClickHandlerEnabled: true\n'
  + '    })),\n'
  + '  }));\n'
  + '}\n'
  + '\n'
  + '// PopoverContext\n'
  + '// =============================================================================\n'
  + '\n'
  + 'const PopoverContext = createContext<StoreApi<PopoverStore> | null>(null);\n'
  + '\n'
  + '// PopoverTrigger\n'
  + '// =============================================================================\n'
  + '\n'
  + 'interface PopoverTriggerRenderProps {\n'
  + '  setRef: (el: Element | null) => void;\n'
  + '\n'
  + '  onClick: MouseEventHandler;\n'
  + '}\n'
  + '\n'
  + 'interface PopoverTriggerProps {\n'
  + '  render: (props: PopoverTriggerRenderProps) => ReactNode\n'
  + '}\n'
  + '\n'
  + 'const PopoverTrigger: FC<PopoverTriggerProps> = (props) => {\n'
  + '  const { render } = props;\n'
  + '\n'
  + '  const context = useContext(PopoverContext);\n'
  + '  if (!context) {\n'
  + "    throw new Error('Popover.Trigger must be used within a Popover');\n"
  + '  }\n'
  + '\n'
  + '  const toggle = useStore(context, (state) => state.toggle);\n'
  + '  const setElRef = useStore(context, (state) => state.setElRef);\n'
  + '  const enableTriggerClickHandler = useStore(context, (state) => state.enableTriggerClickHandler);\n'
  + '  const triggerClickHandlerEnabled = useStore(context, (state) => state.triggerClickHandlerEnabled);\n'
  + '\n'
  + '  const PopoverTriggerRender = useMemo(() => memo(render), [render]);\n'
  + '\n'
  + '  return (\n'
  + '    <PopoverTriggerRender\n'
  + '      setRef={setElRef}\n'
  + '      onClick={() => {\n'
  + '        if (triggerClickHandlerEnabled) {\n'
  + '          toggle();\n'
  + '        } else {\n'
  + '          // Disable because we clicked outside the portal but click the\n'
  + '          // trigger.\n'
  + '          //\n'
  + '          // Now we need to reset it (by enable the trigger click handler).\n'
  + '          enableTriggerClickHandler();\n'
  + '        }\n'
  + '      }}\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  + '\n'
  + "PopoverTrigger.displayName = 'PopoverTrigger';\n"
  + '\n'
  + '// PopoverPortal\n'
  + '// =============================================================================\n'
  + '\n'
  + 'interface PopoverPortalRenderProps {\n'
  + '  setRef: (el: HTMLElement | null) => void;\n'
  + '  togglePortal: () => void;\n'
  + '\n'
  + '  isOpen: boolean;\n'
  + '  floatingStyles: CSSProperties;\n'
  + '}\n'
  + '\n'
  + 'interface OnClickOutsideArgs {\n'
  + '  closePortal: () => void;\n'
  + '}\n'
  + '\n'
  + 'interface PopoverPortalProps {\n'
  + '  onClickOutside?: (args: OnClickOutsideArgs) => void;\n'
  + '\n'
  + '  render: (props: PopoverPortalRenderProps) => ReactNode\n'
  + '}\n'
  + '\n'
  + 'const PopoverPortal: FC<PopoverPortalProps> = (props) => {\n'
  + '  const { onClickOutside, render } = props;\n'
  + '\n'
  + '  const [mounted, setMounted] = useState(false);\n'
  + '  useEffect(() => {\n'
  + '    setMounted(true);\n'
  + '  }, []);\n'
  + '\n'
  + '  const context = useContext(PopoverContext);\n'
  + '  if (!context) {\n'
  + "    throw new Error('Popover.Portal must be used within a Popover');\n"
  + '  }\n'
  + '\n'
  + '  const isOpen = useStore(context, (state) => state.isOpen);\n'
  + '  const floatingStyles = useStore(context, (state) => state.floatingStyles);\n'
  + '  const elRef = useStore(context, (state) => state.elRef);\n'
  + '  const floatingRef = useStore(context, (state) => state.floatingRef);\n'
  + '  const setFloatingRef = useStore(context, (state) => state.setFloatingRef);\n'
  + '  const toggle = useStore(context, (state) => state.toggle);\n'
  + '  const close = useStore(context, (state) => state.close);\n'
  + '  const disablePortalClickHandler = useStore(context, (state) => state.disableTriggerClickHandler);\n'
  + '\n'
  + '  useEffect(() => {\n'
  + '    const floatingRefOriginal = floatingRef;\n'
  + '    if (!floatingRefOriginal) return;\n'
  + '\n'
  + '    /** Check if the click is outside the popover portal */\n'
  + '    function handleClickOutside(event: MouseEvent) {\n'
  + '      if (!floatingRefOriginal || !event.target) return;\n'
  + '\n'
  + '      if (!floatingRefOriginal.contains(event.target as Node)) {\n'
  + '        // Call the handle for click outside.\n'
  + '        onClickOutside?.({\n'
  + '          closePortal: close,\n'
  + '        });\n'
  + '\n'
  + '        if (elRef) {\n'
  + '          const elRefOriginal = elRef;\n'
  + '          function handleMouseUp(event: MouseEvent) {\n'
  + '            event.preventDefault();\n'
  + '\n'
  + '            // If we clicked on the `elRef` (trigger), we need to disable the\n'
  + '            // trigger click handler (then the trigger will ignore the following\n'
  + '            // click event & enable the handler for the next click).\n'
  + '            if (elRefOriginal.contains(event.target as Node)) {\n'
  + '              disablePortalClickHandler();\n'
  + '            }\n'
  + '\n'
  + '            document.removeEventListener("mouseup", handleMouseUp);\n'
  + '          }\n'
  + '          document.addEventListener("mouseup", handleMouseUp);\n'
  + '        }\n'
  + '      }\n'
  + '    }\n'
  + '\n'
  + '    document.addEventListener("mousedown", handleClickOutside);\n'
  + '    return () => {\n'
  + '      document.removeEventListener("mousedown", handleClickOutside);\n'
  + '    };\n'
  + '  }, [floatingRef]);\n'
  + '\n'
  + '  const PopoverPortalRender = useMemo(() => memo(render), [render]);\n'
  + '\n'
  + '  if (!mounted) return null;\n'
  + '\n'
  + '  return createPortal(\n'
  + '    <PopoverPortalRender\n'
  + '      setRef={setFloatingRef}\n'
  + '      togglePortal={toggle}\n'
  + '      isOpen={isOpen}\n'
  + '      floatingStyles={floatingStyles}\n'
  + '    />,\n'
  + '    document.body\n'
  + '  );\n'
  + '}\n'
  + '\n'
  + "PopoverPortal.displayName = 'PopoverPortal';\n"
  + '\n'
  + '// Popover\n'
  + '// =============================================================================\n'
  + '\n'
  + 'export type PopoverProps = {\n'
  + '  children: ReactNode\n'
  + '}\n'
  + '\n'
  + 'type PopoverComponent = FC<PopoverProps> & {\n'
  + '  Trigger: typeof PopoverTrigger;\n'
  + '  Portal: typeof PopoverPortal;\n'
  + '};\n'
  + '\n'
  + 'export const Popover: PopoverComponent = (props) => {\n'
  + '  const { children } = props;\n'
  + '\n'
  + '  const { refs, floatingStyles } = useFloating({\n'
  + "    placement: 'bottom-end',\n"
  + '    whileElementsMounted: autoUpdate,\n'
  + '    middleware: [\n'
  + '      offset(4),\n'
  + '      flip(),\n'
  + '    ],\n'
  + '  });\n'
  + '\n'
  + '  const popoverStore = useMemo(() => {\n'
  + '    return buildPopoverStore({\n'
  + '      onSetElRef: refs.setReference,\n'
  + '      onSetFloatingRef: refs.setFloating,\n'
  + '    });\n'
  + '  }, [refs]);\n'
  + '\n'
  + '  useEffect(() => {\n'
  + '    popoverStore.getState().setFloatingStyles(floatingStyles);\n'
  + '  }, [floatingStyles]);\n'
  + '\n'
  + '  return (\n'
  + '    <PopoverContext value={popoverStore}>\n'
  + '      {children}\n'
  + '    </PopoverContext>\n'
  + '  )\n'
  + '};\n'
  + '\n'
  + "Popover.displayName = 'Popover';\n"
  + '\n'
  + 'Popover.Trigger = PopoverTrigger;\n'
  + 'Popover.Portal = PopoverPortal;\n'
  ;

sourceCode['index.ts'] = ''
  + '// Popover from copy-ui @ 2025-09-22\n'
  + '\n'
  + 'export { Popover } from "./Popover";\n'
  ;

