// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { CodeBlock } from "@/components/CodeBlock";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Markdown } from "@/components/Markdown";\n'
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import content from "./content01.md?raw";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper radius="md" withBorder withPadding>\n'
  + '      <Flex dir="row" gap="1rem">\n'
  + '        <Markdown>{content}</Markdown>\n'
  + '        <CodeBlock code={content} lang="markdown" />\n'
  + '      </Flex>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
