// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Card } from "@/components/Card";\n'
  + 'import { Markdown } from "@/components/Markdown";\n'
  + '\n'
  + 'const content = `\\\n'
  + '# Hello World\n'
  + '\n'
  + 'This is a simple Markdown component demo.\n'
  + '\n'
  + '- Item 1\n'
  + '- Item 2\n'
  + '- Item 3\n'
  + '\n'
  + '\\`\\`\\`tsx\n'
  + '"use Copy UI";\n'
  + '\\`\\`\\`\n'
  + '`;\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Card>\n'
  + '      <Card.Content>\n'
  + '        <Markdown>{content}</Markdown>\n'
  + '      </Card.Content>\n'
  + '    </Card>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
