// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Markdown } from "@/components/Markdown";\n'
  + '\n'
  + 'const content = `\\\n'
  + '# Hello World\n'
  + '\n'
  + 'This is a simple Markdown component demo.\n'
  + '\n'
  + '- Item 1\n'
  + '- Item 2\n'
  + '- Item 3\n'
  + '`;\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Markdown>{content}</Markdown>;\n'
  + '}\n'
  ;

export default demoSourceCode;
