// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { ChevronRight } from "lucide-react";\n'
  + 'import { Breadcrumb } from "@/components/Breadcrumb";\n'
  + '\n'
  + 'const Sep = () => (\n'
  + '  <Breadcrumb.Sep>\n'
  + '    <ChevronRight />\n'
  + '  </Breadcrumb.Sep>\n'
  + ');\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Breadcrumb>\n'
  + '      <Breadcrumb.Item>Home</Breadcrumb.Item>\n'
  + '      <Sep />\n'
  + '      <Breadcrumb.Item>Components</Breadcrumb.Item>\n'
  + '      <Sep />\n'
  + '      <Breadcrumb.Item current>Breadcrumb</Breadcrumb.Item>\n'
  + '    </Breadcrumb>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
