// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Breadcrumb } from "@/components/Breadcrumb";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const sizes = ["sm", "md", "lg"] as const;\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      {sizes.map((size) => (\n'
  + '        <Breadcrumb size={size} key={size}>\n'
  + '          <Breadcrumb.Item>Home</Breadcrumb.Item>\n'
  + '          <Breadcrumb.Sep />\n'
  + '          <Breadcrumb.Item>Components</Breadcrumb.Item>\n'
  + '          <Breadcrumb.Sep />\n'
  + '          <Breadcrumb.Item current>Breadcrumb</Breadcrumb.Item>\n'
  + '        </Breadcrumb>\n'
  + '      ))}\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
