// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-10: Initial version.\n'
  + '- 2025-10-12: Add `Field.Select` component.\n'
  + '- 2025-10-27: Add `Field.TextArea` component.\n'
  ;
