// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-10): Initial version.\n'
  + '- 0.1.1 (2025-10-12): Add `Field.Select` component.\n'
  + '- 0.1.2 (2025-10-27): Add `Field.TextArea` component.\n'
  + '- 0.1.3 (2025-11-08): Refactor code structure.\n'
  + '- 0.1.4 (2025-11-21): Add `Field.FileInput` component. And remove useless style\n'
  + '  `width: 100%`.\n'
  + '- 0.1.5 (2025-12-17): Export the `useOptionalFieldContext` hook.\n'
  + '- 0.1.6 (2026-02-14): Use a semantic `fieldset` wrapper and remove\n'
  + '  `biome-ignore`.\n'
  ;
