// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-30: Initial version.\n'
  + '- 2025-10-02: Add `leftSection` and `rightSection` props for flexible input\n'
  + '  layouts. Add `wrapperClassName` and `style` props for custom styling. Improve\n'
  + '  component structure with proper wrapper and section styling. Update import\n'
  + '  paths and code formatting.\n'
  + '- 2025-10-20: Support `disabled` prop.\n'
  + '- 2025-10-24: Support the `className` prop.\n'
  ;
