// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + '// InputBase from copy-ui @ 2025-09-30.\n'
  + '\n'
  + 'export { InputBase } from "./InputBase";\n'
  ;

sourceCode['InputBase.tsx'] = ''
  + 'import { merge } from "es-toolkit";\n'
  + 'import type { CSSProperties, FC } from "react";\n'
  + '\n'
  + 'import styles from "./InputBase.module.scss";\n'
  + 'import { useTheme } from "../ThemeProvider";\n'
  + '\n'
  + 'interface InputBaseProps {\n'
  + '  children?: React.ReactNode;\n'
  + "  size?: 'sm' | 'md' | 'lg';\n"
  + '}\n'
  + '\n'
  + 'export const InputBase: FC<InputBaseProps> = (props) => {\n'
  + "  const { size = 'md', children } = props;\n"
  + '\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const computedStyle = mergeStyles([\n'
  + "    size === 'sm' && {\n"
  + "      '--input-base-height': theme.tokens.inputBaseSmHeight,\n"
  + '    } as CSSProperties,\n'
  + "    size === 'md' && {\n"
  + "      '--input-base-height': theme.tokens.inputBaseMdHeight,\n"
  + '    } as CSSProperties,\n'
  + "    size === 'lg' && {\n"
  + "      '--input-base-height': theme.tokens.inputBaseLgHeight,\n"
  + '    } as CSSProperties,\n'
  + '    {\n'
  + "      '--input-base-min-width': '16rem',\n"
  + "      '--input-base-border-color': theme.tokens.inputBaseDefaultBorderColor,\n"
  + "      '--input-base-border-radius': theme.tokens.inputBaseBorderRadius,\n"
  + '    } as CSSProperties,\n'
  + '  ]);\n'
  + '\n'
  + '  return (\n'
  + '    <div style={computedStyle} className={styles.inputBase}>\n'
  + '      {children}\n'
  + '    </div>\n'
  + '  )\n'
  + '};\n'
  + '\n'
  + 'InputBase.displayName = "InputBase";\n'
  + '\n'
  + 'function mergeStyles(styles: (CSSProperties | false | undefined)[]) {\n'
  + '  return styles.reduce((prev, next) => {\n'
  + '    return next ? merge(prev as CSSProperties, next) : prev;\n'
  + '  }, {}) as CSSProperties;\n'
  + '}\n'
  ;

sourceCode['InputBase.module.scss'] = ''
  + '.inputBase {\n'
  + '  display: inline-flex;\n'
  + '  \n'
  + '  height: var(--input-base-height);\n'
  + '  min-width: var(--input-base-min-width);\n'
  + '\n'
  + '  border-width: 1px;\n'
  + '  border-style: solid;\n'
  + '  border-color: var(--input-base-border-color);\n'
  + '  border-radius: var(--input-base-border-radius);\n'
  + '\n'
  + '  background-color: white;\n'
  + '\n'
  + '  overflow: hidden;\n'
  + '}\n'
  ;

