// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-11-21): Initial version.\n'
  + '- 0.1.1 (2025-12-08): Use `IbsBase` rather than the deprecated `InputBase`\n'
  + '  component.\n'
  + '- 0.1.2 (2026-02-13): Use `IbsBaseStyleProps` in `FileInputProps` and keep\n'
  + '  custom `onChange` typing to avoid root event type pollution.\n'
  ;
