// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-11-30): Initial version.\n'
  + '- 0.1.1 (2025-12-12): Update the styles - padding and gap - to make it look\n'
  + '  better.\n'
  + '- 0.1.2 (2025-12-13): Update to make it look good with new colors.\n'
  + '- 0.1.3 (2026-02-12): Update the styles to make it looks better.\n'
  ;
