// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-12-07: Initial version.\n'
  + '- 2025-12-16: Use `min-height` instead of `height` to let components built on\n'
  + '  top of it to have a flexible height.\n'
  ;
