// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-12-07): Initial version.\n'
  + '- 0.1.1 (2025-12-16): Use `min-height` instead of `height` to let components\n'
  + '  built on top of it to have a flexible height.\n'
  + "- 0.1.2 (2026-02-12): Update the filled variant's background color.\n"
  + '- 0.1.3 (2026-02-13): Export `IbsBaseStyleProps` and `IbsBaseRootProps` to\n'
  + '  provide a stable style/root contract for components built on top of `IbsBase`.\n'
  ;
