// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-23: Initial version.\n'
  + '- 2025-09-25: Allow props to accept generics.\n'
  + "- 2025-09-25: Use `onToggle` instead of `onClick` in `Popover.Trigger`'s render\n"
  + '  prop.\n'
  + '- 2025-10-03: Fix missing dependencies in useEffect hooks, etc.\n'
  + '- 2025-10-11: Support `id` prop for better form integration. Make it be able to\n'
  + '  uncontrolled. Support `defaultValue` prop. Code formatting improvements.\n'
  + '- 2025-10-26: Update styles (padding) to make it look better.\n'
  ;
