// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-23: Initial version.\n'
  + '- 2025-09-25: Allow props to accept generics.\n'
  + "- 2025-09-25: Use `onToggle` instead of `onClick` in `Popover.Trigger`'s render\n"
  + '  prop.\n'
  + '- 2025-10-03: Fix missing dependencies in useEffect hooks, etc.\n'
  + '- 2025-10-11: Support `id` prop for better form integration. Make it be able to\n'
  + '  uncontrolled. Support `defaultValue` prop. Code formatting improvements.\n'
  + '- 2025-10-26: Update styles (padding) to make it look better.\n'
  + '- 2025-10-27: Update styles when Select is opened or focused. Make its\n'
  + '  `min-width` be `8rem` now (rather than `16rem`).\n'
  + '- 2025-10-28: Refactor code to make code cleaner. Add a small gap in trigger.\n'
  + '- 2025-10-30: Add a `ResizeObserver` to the `Select.Trigger` to update the\n'
  + "  `Select.List`'s width when the trigger size changes.\n"
  + '- 2025-10-31: Add the check mark for the selected item in the list.\n'
  + '- 2025-11-04: Wrap the list with `ScrollArea` to make it scrollable when there\n'
  + '  are many options.\n'
  + '- 2025-11-21: Add `width` prop to control the width of the component. Remove the\n'
  + '  `min-width` constraint on the trigger. And remove the dependency on\n'
  + '  `ThemeProvider`.\n'
  ;
