export const sourceCode: Record<string, string> = {};

sourceCode['Select.module.scss'] = ''
  + '.selectMain {\n'
  + '  display: flex;\n'
  + '  align-items: center;\n'
  + '\n'
  + '  padding-inline: 0.5rem;\n'
  + '\n'
  + '  height: var(--select-main-height);\n'
  + '  min-width: 16rem;\n'
  + '\n'
  + '  border-width: 1px;\n'
  + '  border-style: solid;\n'
  + '  border-color: var(--select-main-border-color);\n'
  + '  border-radius: var(--select-main-border-radius);\n'
  + '\n'
  + '  background-color: white;\n'
  + '\n'
  + '  font-size: var(--select-font-size);\n'
  + '\n'
  + '  cursor: pointer;\n'
  + '  user-select: none;\n'
  + '\n'
  + '  &[data-value-picked="false"] {\n'
  + '    color: var(--select-main-placeholder-color);\n'
  + '  }\n'
  + '  &[data-disabled="true"] {\n'
  + '    background-color: var(--select-main-disabled-bg-color);\n'
  + '    border-color: var(--select-main-disabled-border-color);\n'
  + '    color: var(--select-main-disabled-color);\n'
  + '    cursor: not-allowed;\n'
  + '  }\n'
  + '}\n'
  + '\n'
  + '.selectIcon {\n'
  + '  display: flex;\n'
  + '  align-items: center;\n'
  + '  justify-content: center;\n'
  + '\n'
  + '  width: var(--select-line-height);\n'
  + '  height: var(--select-line-height);\n'
  + '}\n'
  + '\n'
  + '.selectList {\n'
  + '  display: flex;\n'
  + '  flex-direction: column;\n'
  + '  gap: 0.125rem;\n'
  + '\n'
  + '  width: var(--select-list-width);\n'
  + '\n'
  + '  padding: 0.125rem;\n'
  + '\n'
  + '  border-width: 1px;\n'
  + '  border-style: solid;\n'
  + '  border-color: var(--select-list-border-color);\n'
  + '  border-radius: var(--select-list-border-radius);\n'
  + '\n'
  + '  background-color: white;\n'
  + '\n'
  + '  font-size: var(--select-font-size);\n'
  + '}\n'
  + '\n'
  + '.selectItem {\n'
  + '  padding: 0.25rem 0.375rem;\n'
  + '\n'
  + '  border-radius: calc(var(--select-list-border-radius) * 0.5);\n'
  + '\n'
  + '  cursor: pointer;\n'
  + '  user-select: none;\n'
  + '\n'
  + '  &:hover {\n'
  + '    background-color: var(--select-item-hover-bg-color);\n'
  + '  }\n'
  + '}\n'
  ;

sourceCode['index.ts'] = ''
  + '// Select from copy-ui @ 2025-09-23.\n'
  + '\n'
  + 'export { Select } from "./Select";\n'
  ;

sourceCode['Select.tsx'] = ''
  + 'import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties, type FC } from "react"\n'
  + 'import { Popover } from "../Popover";\n'
  + '\n'
  + 'import { useTheme } from "../ThemeProvider";\n'
  + '\n'
  + 'import styles from "./Select.module.scss";\n'
  + 'import { ChevronsUpDown } from "lucide-react";\n'
  + '\n'
  + 'interface SelectProps {\n'
  + '  value?: string | null;\n'
  + '\n'
  + '  options: Array<{ value: string; label: string }>;\n'
  + '  placeholder?: string;\n'
  + '  disabled?: boolean;\n'
  + '\n'
  + '  onChange?: (value: string) => void;\n'
  + '}\n'
  + '\n'
  + 'const Select: FC<SelectProps> = (props) => {\n'
  + '  const {\n'
  + '    value = null,\n'
  + '\n'
  + '    options,\n'
  + "    placeholder = 'Select an option',\n"
  + '    disabled = false,\n'
  + '\n'
  + '    onChange,\n'
  + '  } = props;\n'
  + '\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const mainRef = useRef<HTMLDivElement | null>(null);\n'
  + '\n'
  + '  const [selectedOptionValue, setSelectedOptionValue] = useState<string | null>(value);\n'
  + '  const showLabel = selectedOptionValue ? options.find(o => o.value === selectedOptionValue)?.label : null;\n'
  + '\n'
  + '  const [mainWidth, setMainWidth] = useState(0);\n'
  + '\n'
  + '  useEffect(() => {\n'
  + '    if (value === selectedOptionValue) return;\n'
  + '    setSelectedOptionValue(value ?? null);\n'
  + '  }, [value]);\n'
  + '\n'
  + '  const mainStyle = {\n'
  + "    '--select-font-size': theme.tokens.inputBaseMdFontSize,\n"
  + "    '--select-line-height': theme.tokens.inputBaseMdLineHeight,\n"
  + '\n'
  + "    '--select-main-height': theme.tokens.inputBaseMdHeight,\n"
  + "    '--select-main-border-color': theme.tokens.inputBaseDefaultBorderColor,\n"
  + "    '--select-main-border-radius': theme.tokens.inputBaseBorderRadius,\n"
  + "    '--select-main-placeholder-color': theme.tokens.inputBasePlaceholderColor,\n"
  + '\n'
  + "    '--select-main-disabled-color': theme.colors.gray['600'],\n"
  + "    '--select-main-disabled-bg-color': theme.colors.gray['000'],\n"
  + "    '--select-main-disabled-border-color': theme.colors.gray['200'],\n"
  + '  }\n'
  + '\n'
  + '  const listStyle = {\n'
  + "    '--select-font-size': theme.tokens.inputBaseMdFontSize,\n"
  + "    '--select-line-height': theme.tokens.inputBaseMdLineHeight,\n"
  + '\n'
  + "    '--select-list-width': `${mainWidth}px`,\n"
  + "    '--select-list-border-color': theme.tokens.inputBaseDefaultBorderColor,\n"
  + "    '--select-list-border-radius': theme.tokens.inputBaseBorderRadius,\n"
  + '\n'
  + "    '--select-item-hover-bg-color': theme.colors.gray['000'],\n"
  + '  }\n'
  + '\n'
  + '  useLayoutEffect(() => {\n'
  + '    const main = mainRef.current;\n'
  + '    if (main) {\n'
  + '      setMainWidth(main.offsetWidth);\n'
  + '    }\n'
  + '  }, []);\n'
  + '\n'
  + '  return (\n'
  + '    <Popover>\n'
  + '      <Popover.Trigger\n'
  + '        render={({ setRef, onClick }) => (\n'
  + '          <div\n'
  + '            ref={(el) => { setRef(el); mainRef.current = el; }}\n'
  + '            className={styles.selectMain}\n'
  + '            style={mainStyle as CSSProperties}\n'
  + '            onClick={(e) => !disabled && onClick(e)}\n'
  + '\n'
  + '            data-value-picked={selectedOptionValue == null ? "false" : "true"}\n'
  + '            data-disabled={disabled ? "true" : "false"}\n'
  + '          >\n'
  + '            <span style={{ flex: 1 }}>\n'
  + '              {showLabel ? showLabel : placeholder}\n'
  + '            </span>\n'
  + '            <span className={styles.selectIcon}>\n'
  + "              <ChevronsUpDown size='62.5%' />\n"
  + '            </span>\n'
  + '          </div>\n'
  + '        )}\n'
  + '      />\n'
  + '      <Popover.Portal\n'
  + '        onClickOutside={({ closePortal }) => closePortal()}\n'
  + '        render={({ setRef, togglePortal, isOpen, floatingStyles }) => (\n'
  + '          isOpen && (\n'
  + '            <ul\n'
  + '              ref={setRef}\n'
  + '              className={styles.selectList}\n'
  + '              style={{ ...listStyle, ...floatingStyles }}\n'
  + '            >\n'
  + '              {options.map((option) => (\n'
  + '                <li\n'
  + '                  key={option.value}\n'
  + '                  className={styles.selectItem}\n'
  + '                  onClick={() => {\n'
  + '                    togglePortal();\n'
  + '\n'
  + '                    if (!disabled) {\n'
  + '                      setSelectedOptionValue(option.value);\n'
  + '                      onChange?.(option.value);\n'
  + '                    }\n'
  + '                  }}\n'
  + '                >\n'
  + '                  {option.label}\n'
  + '                </li>\n'
  + '              ))}\n'
  + '            </ul>\n'
  + '          )\n'
  + '        )}\n'
  + '      />\n'
  + '    </Popover>\n'
  + '  )\n'
  + '}\n'
  + '\n'
  + 'Select.displayName = "Select";\n'
  + '\n'
  + 'export { Select };\n'
  ;

