// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + 'import { FileInput } from "@/components/FileInput";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const stx = jss.hash({\n'
  + '    width: "30rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem" className={stx}>\n'
  + '      <FileInput width="sm" placeholder="Choose file..." />\n'
  + '      <FileInput width="md" placeholder="Choose file..." />\n'
  + '      <FileInput width="lg" placeholder="Choose file..." />\n'
  + '      <FileInput width="full" placeholder="Choose file..." />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
