// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { FileInput } from "@/components/FileInput";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <FileInput placeholder="Choose file..." />;\n'
  + '}\n'
  ;

export default demoSourceCode;
