// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { FileInput } from "@/components/FileInput";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <FileInput w="12rem" placeholder="Choose file..." />;\n'
  + '}\n'
  ;
;

export default sourceCode;
