// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { FileInput } from "@/components/FileInput";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem">\n'
  + '      <FileInput size="xs" w="16rem" placeholder="Choose file..." />\n'
  + '      <FileInput size="sm" w="16rem" placeholder="Choose file..." />\n'
  + '      <FileInput size="md" w="16rem" placeholder="Choose file..." />\n'
  + '      <FileInput size="lg" w="16rem" placeholder="Choose file..." />\n'
  + '      <FileInput size="xl" w="16rem" placeholder="Choose file..." />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
