// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { Button } from "@/components/Button";\n'
  + 'import { useToast } from "@/components/Toast";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const { addToast } = useToast();\n'
  + '  const [counter, setCounter] = useState(1);\n'
  + '\n'
  + '  const handleAddToast = () => {\n'
  + '    const type = (["default", "success", "info", "warning", "error"] as const)[\n'
  + '      Math.floor(Math.random() * 5)\n'
  + '    ];\n'
  + '    addToast({\n'
  + '      type,\n'
  + '      message: `This is toast message ${counter}`,\n'
  + '      description: "You can send more toasts, if you like.",\n'
  + '    });\n'
  + '    setCounter(counter + 1);\n'
  + '  };\n'
  + '\n'
  + '  return <Button onClick={handleAddToast}>Add Toast</Button>;\n'
  + '}\n'
  ;

export default demoSourceCode;
