// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const components: { name: string, path: string, wip: boolean }[] = [
  {"name": "Avatar", "path": "/v0/components/Avatar", "wip": false},
  {"name": "Background", "path": "/v0/components/Background", "wip": false},
  {"name": "Button", "path": "/v0/components/Button", "wip": false},
  {"name": "ButtonGroup", "path": "/v0/components/ButtonGroup", "wip": false},
  {"name": "Calendar", "path": "/v0/components/Calendar", "wip": false},
  {"name": "CodeHighlight", "path": "/v0/components/CodeHighlight", "wip": false},
  {"name": "DatePicker", "path": "/v0/components/DatePicker", "wip": true},
  {"name": "Flex", "path": "/v0/components/Flex", "wip": false},
  {"name": "IconButton", "path": "/v0/components/IconButton", "wip": false},
  {"name": "Input", "path": "/v0/components/Input", "wip": false},
  {"name": "InputBase", "path": "/v0/components/InputBase", "wip": false},
  {"name": "Popover", "path": "/v0/components/Popover", "wip": false},
  {"name": "ScrollArea", "path": "/v0/components/ScrollArea", "wip": false},
  {"name": "Select", "path": "/v0/components/Select", "wip": false},
  {"name": "SortIndicator", "path": "/v0/components/SortIndicator", "wip": false},
  {"name": "Switch", "path": "/v0/components/Switch", "wip": false},
  {"name": "Tabs", "path": "/v0/components/Tabs", "wip": false},
  {"name": "Tag", "path": "/v0/components/Tag", "wip": false},
  {"name": "ThemeProvider", "path": "/v0/components/ThemeProvider", "wip": false},
  {"name": "TimeSelector", "path": "/v0/components/TimeSelector", "wip": false},
  {"name": "Toast", "path": "/v0/components/Toast", "wip": false},
  {"name": "Tooltip", "path": "/v0/components/Tooltip", "wip": false},
  {"name": "Typography", "path": "/v0/components/Typography", "wip": false},
];
