// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const components: { name: string, path: string }[] = [
  {"name": "Avatar", "path": "/v0/components/Avatar"},
  {"name": "Button", "path": "/v0/components/Button"},
  {"name": "ButtonGroup", "path": "/v0/components/ButtonGroup"},
  {"name": "CodeHighlight", "path": "/v0/components/CodeHighlight"},
  {"name": "DatePicker", "path": "/v0/components/DatePicker"},
  {"name": "IconButton", "path": "/v0/components/IconButton"},
  {"name": "Input", "path": "/v0/components/Input"},
  {"name": "Popover", "path": "/v0/components/Popover"},
  {"name": "Select", "path": "/v0/components/Select"},
  {"name": "SortIndicator", "path": "/v0/components/SortIndicator"},
  {"name": "Tag", "path": "/v0/components/Tag"},
  {"name": "ThemeProvider", "path": "/v0/components/ThemeProvider"},
  {"name": "TimeSelector", "path": "/v0/components/TimeSelector"},
  {"name": "Toast", "path": "/v0/components/Toast"},
  {"name": "Tooltip", "path": "/v0/components/Tooltip"},
];
