// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const utils: { name: string, path: string }[] = [
  {"name": "jss", "path": "/v0/react/utils/jss"},
  {"name": "resolve-style2", "path": "/v0/react/utils/resolve-style2"},
];
