// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const utils: { name: string, path: string }[] = [
  {"name": "resolve-style", "path": "/v0/utils/resolve-style"},
];
