// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-12: Initial version.\n'
  + '- 2025-09-26: Add support for TSX language in CodeHighlight.\n'
  + '- 2025-10-05: Add `withLineNumbers` prop to CodeHighlight component.\n'
  + "- 2025-10-11: Update line-numbers' style.\n"
  + '- 2025-10-16: Refactor code to use hast to build the HTML. That make the\n'
  + '  `CodeHighlight` component support `lineHighlight` prop, etc.\n'
  + '- 2025-10-22: Refactor code. And use JSS for styling.\n'
  ;
