// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-12): Initial version.\n'
  + '- 0.1.1 (2025-09-26): Add support for TSX language in CodeHighlight.\n'
  + '- 0.1.2 (2025-10-05): Add `withLineNumbers` prop to CodeHighlight component.\n'
  + "- 0.1.3 (2025-10-11): Update line-numbers' style.\n"
  + '- 0.1.4 (2025-10-16): Refactor code to use hast to build the HTML. That make the\n'
  + '  `CodeHighlight` component support `lineHighlight` prop, etc.\n'
  + '- 0.1.5 (2025-10-22): Refactor code. And use JSS for styling.\n'
  + '- 0.1.6 (2025-12-08): Support the highlighting for CSS language, remove the\n'
  + '  dependency on `ThemeProvider`, etc.\n'
  + '- 0.1.7 (2025-12-12): Support the `className` prop to CodeHighlight component.\n'
  ;
