// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-02: Initial version (with Typography.H1 component only).\n'
  + '- 2025-10-03: Added Typography.H2, Typography.H3 and Typography.P components.\n'
  + '  Support the `mt` prop for margin-top spacing & update CSS styles.\n'
  ;
