// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-02: Initial version (with Typography.H1 component).\n'
  + '- 2025-10-03: Added Typography.H2, Typography.H3 and Typography.P components.\n'
  + '  Support the `mt` prop for margin-top spacing & update CSS styles to make it\n'
  + '  look better.\n'
  + '- 2025-10-04: Add Typography.H4 component. Support `mb` prop for margin-bottom\n'
  + '  spacing. Increase H1 font size and improve prop handling consistency.\n'
  ;
