// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-02: Initial version (with `Typography.H1` component).\n'
  + '- 2025-10-03: Added `Typography.H2`, `Typography.H3` and `Typography.P`\n'
  + '  components. Support the `mt` prop for margin-top spacing & update CSS styles\n'
  + '  to make it look better.\n'
  + '- 2025-10-04: Add `Typography.H4` component. Support `mb` prop for margin-bottom\n'
  + '  spacing. Increase `H1` font size and improve prop handling consistency.\n'
  + '- 2025-10-05: Add `Typography.Ul` and `Typography.Li` components. Also add\n'
  + '  default styles for `Typography.P`.\n'
  + '- 2025-10-10: Add `Typography.Code` component for inline code.\n'
  ;
