// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <div style={{ display: "flex", flexDirection: "column" }}>\n'
  + '      <Typography.H1>This is a heading 1</Typography.H1>\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
