// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['Typography.module.scss'] = ''
  + '.h1 {\n'
  + '  font-size: 2.25rem;\n'
  + '  line-height: 2.5rem;\n'
  + '  font-weight: 800;\n'
  + '}\n'
  ;

sourceCode['Typography.tsx'] = ''
  + 'import classNames from "classnames";\n'
  + 'import type { ComponentProps, FC } from "react";\n'
  + '\n'
  + 'import styles from "./Typography.module.scss";\n'
  + '\n'
  + '// Typography.H1\n'
  + '// =============================================================================\n'
  + '\n'
  + 'type TypographyH1Props = ComponentProps<"h1">;\n'
  + '\n'
  + 'const TypographyH1: FC<TypographyH1Props> = (props) => {\n'
  + '  const { children, className, ...rest } = props;\n'
  + '\n'
  + '  return (\n'
  + '    <h1 className={classNames(styles.h1, className)} {...rest}>\n'
  + '      {children}\n'
  + '    </h1>\n'
  + '  );\n'
  + '};\n'
  + '\n'
  + '// Typography\n'
  + '// =============================================================================\n'
  + '\n'
  + 'type TypographyType = {\n'
  + '  H1: typeof TypographyH1;\n'
  + '};\n'
  + '\n'
  + 'const Typography: TypographyType = {\n'
  + '  H1: TypographyH1,\n'
  + '};\n'
  + '\n'
  + 'export { Typography };\n'
  ;

sourceCode['index.ts'] = ''
  + '// Typography from copy-ui @ 2025-10-02.\n'
  + '\n'
  + 'export { Typography } from "./Typography";\n'
  ;

