// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-04: Initial version.\n'
  + '- 2025-09-05: Use ThemeProvider for theming, support the props `leftSection` and\n'
  + '  `rightSection`.\n'
  + '- 2025-09-08: Support the prop `ref`.\n'
  + '- 2025-09-09: Support the prop `variant`.\n'
  + '- 2025-09-18: Support the prop `size` (`sm`, `md` and `lg`).\n'
  + "- 2025-09-23: Update the default button's border color. Add `justify-content:\n"
  + '  center` to the button styles.\n'
  + '- 2025-09-29: Make the prop `size` support `xs` and `xl` values & use tokens\n'
  + '  from ThemeProvider.\n'
  + '- 2025-10-04: Add `ghost` variant. Code formatting improvement.\n'
  + '- 2025-10-08: Add `light` variant, update `ghost` variant styles.\n'
  + '- 2025-10-15: Support change styles when `disabled`.\n'
  + '- 2025-10-20: Support the prop `color`.\n'
  + '- 2025-10-28: Add `secondary` variant.\n'
  + '- 2025-10-30: Add `--button-border-separator-color` CSS variable and add the\n'
  + '  default icon size for SVG children in left or right section.\n'
  ;
