// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Star } from "lucide-react";\n'
  + 'import { Button } from "src/components/Button";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + "    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>\n"
  + '      <Button size="xs" leftSection={<Star size="1rem" />}>Oh</Button>\n'
  + '      <Button size="sm">Oh</Button>\n'
  + '      <Button>Hello</Button>\n'
  + '      <Button size="lg" variant="filled">World</Button>\n'
  + '      <Button size="xl">And you</Button>\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
