// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-27: Initial version.\n'
  + '- 2025-11-28: Update its styles to match the style of `Input` component.\n'
  ;
