// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-27): Initial version.\n'
  + '- 0.1.1 (2025-11-28): Update its styles to match the style of `Input` component.\n'
  ;
