// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { CodeHighlight } from "src/components/CodeHighlight/CodeHighlight";\n'
  + 'import { useTheme } from "src/components/ThemeProvider";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'const code = `\\\n'
  + '/**\n'
  + " * Return the string 'foobar'.\n"
  + ' */\n'
  + 'function foobar() {\n'
  + "  return 'foobar';\n"
  + '}\n'
  + '`;\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const style = {\n'
  + '    backgroundColor: theme.colors.gray["000"],\n'
  + '    padding: "1rem",\n'
  + '    borderRadius: "0.5rem",\n'
  + '    width: "40rem",\n'
  + '  };\n'
  + '\n'
  + '  return (\n'
  + '    <Flex style={style}>\n'
  + '      <CodeHighlight code={code} lang="typescript" withLineNumbers />\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
