// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { CodeHighlight } from "@/components/CodeHighlight";\n'
  + 'import { useTheme } from "@/components/ThemeProvider";\n'
  + '\n'
  + 'const code = `\\\n'
  + '/**\n'
  + " * Return the string 'foobar'.\n"
  + ' */\n'
  + 'function foobar() {\n'
  + "  return 'foobar';\n"
  + '}\n'
  + '`;\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '\n'
  + '  const style = {\n'
  + '    backgroundColor: theme.colors.gray["000"],\n'
  + '    borderRadius: "0.5rem",\n'
  + '    width: "40rem",\n'
  + '  };\n'
  + '\n'
  + '  return (\n'
  + '    <CodeHighlight\n'
  + '      code={code}\n'
  + '      lang="typescript"\n'
  + '      withLineNumbers\n'
  + '      lineHighlight={{ ge: 4, lt: 7 }}\n'
  + '      style={style}\n'
  + '      px="1.5rem"\n'
  + '      py="0.75rem"\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
