// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { CodeHighlight } from "@/components/CodeHighlight";\n'
  + 'import { useJss, useTheme } from "@/components/CopyUiProvider";\n'
  + '\n'
  + 'import code from "./code.txt?raw";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const theme = useTheme();\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const stx = jss.hash({\n'
  + '    backgroundColor: theme.colors.gray["000"],\n'
  + '    borderRadius: "0.5rem",\n'
  + '    width: "40rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <CodeHighlight\n'
  + '      code={code}\n'
  + '      lang="typescript"\n'
  + '      withLineNumbers\n'
  + '      lineHighlight={{ ge: 4, lt: 7 }}\n'
  + '      className={stx}\n'
  + '      px="1.5rem"\n'
  + '      py="0.75rem"\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;
sourceCode['code.txt'] = ''
  + '/**\n'
  + " * Return the string 'foobar'.\n"
  + ' */\n'
  + 'function foobar() {\n'
  + "  return 'foobar';\n"
  + '}\n'
  ;
;

export default sourceCode;
