// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { Resizable } from "@/components/Resizable";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Paper radius="md" withBorder style={{ height: "20rem", width: "100%" }}>\n'
  + '      <Resizable.PanelGroup direction="horizontal">\n'
  + '        <Resizable.Panel defaultSize={30} minSize={20}>\n'
  + '          <Paper withPadding>\n'
  + '            This is the left panel. You can drag the divider to resize it.\n'
  + '          </Paper>\n'
  + '        </Resizable.Panel>\n'
  + '        <Resizable.Handle />\n'
  + '        <Resizable.Panel defaultSize={70} minSize={30}>\n'
  + '          <Paper withPadding>\n'
  + '            This is the right panel. Drag the divider between the panels to\n'
  + '            adjust their sizes.\n'
  + '          </Paper>\n'
  + '        </Resizable.Panel>\n'
  + '      </Resizable.PanelGroup>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
