// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-09: Initial version.\n'
  + '- 2025-09-19: Support the prop `size` (`sm`, `md` and `lg`).\n'
  + '- 2025-09-26: Use theme tokens for styling.\n'
  + '- 2025-10-11: Code formatting improvements.\n'
  ;
