// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-09): Initial version.\n'
  + '- 0.1.1 (2025-09-19): Support the prop `size` (`sm`, `md` and `lg`).\n'
  + '- 0.1.2 (2025-09-26): Use theme tokens for styling.\n'
  + '- 0.1.3 (2025-10-11): Code formatting improvements.\n'
  + '- 0.1.4 (2025-10-30): Add the default icon size for SVG children.\n'
  + '- 0.1.5 (2025-11-23): Update the CSS variables names with camelCase.\n'
  ;
