// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Trash } from "lucide-react";\n'
  + '\n'
  + 'import { IconButton } from "src/components/IconButton";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + "    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>\n"
  + '      <IconButton size="sm">\n'
  + "        <Trash size={'60%'} />\n"
  + '      </IconButton>\n'
  + '      <IconButton>\n'
  + "        <Trash size={'60%'} />\n"
  + '      </IconButton>\n'
  + '      <IconButton size="lg" variant="filled">\n'
  + "        <Trash size={'60%'} />\n"
  + '      </IconButton>\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
