// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-21): Initial version.\n'
  + '- 0.1.1 (2025-10-31): Add the sub-component `Card.Footer`, update styles to make\n'
  + '  it looks better, etc.\n'
  + '- 0.1.2 (2025-11-25): Add the sub-component `Card.ContentInScrollArea`, and\n'
  + '  support the `withBorder` prop for `Card.Header` and `Card.Footer`. Some styles\n'
  + '  are updated to make it looks better.\n'
  + '- 0.1.3 (2025-12-07): Add the `withTypography` prop to `Card.Content` and\n'
  + '  `Card.ContentInScrollArea`.\n'
  ;
