// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['card.tsx'] = ''
  + 'import type { ComponentProps, FC } from "react";\n'
  + '\n'
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { CardContent } from "./card-content";\n'
  + 'import { CardHeader } from "./card-header";\n'
  + '\n'
  + 'type CardProps = ComponentProps<typeof Paper>;\n'
  + '\n'
  + 'type CardComponent = FC<CardProps> & {\n'
  + '  Header: typeof CardHeader;\n'
  + '  Content: typeof CardContent;\n'
  + '};\n'
  + '\n'
  + 'const Card: CardComponent = (props: CardProps) => {\n'
  + '  return <Paper style={{ width: "20rem" }} radius="md" withBorder {...props} />;\n'
  + '};\n'
  + '\n'
  + 'Card.displayName = "Card";\n'
  + '\n'
  + 'Card.Header = CardHeader;\n'
  + 'Card.Content = CardContent;\n'
  + '\n'
  + 'export { Card };\n'
  ;

sourceCode['card-header.module.scss'] = ''
  + '.cardHeader {\n'
  + '  padding: 1rem 1rem 0 1rem;\n'
  + '  font-size: 1.25rem;\n'
  + '  font-weight: 600;\n'
  + '}\n'
  ;

sourceCode['card-content.tsx'] = ''
  + 'import type { FC } from "react";\n'
  + '\n'
  + 'import styles from "./card-content.module.scss";\n'
  + '\n'
  + 'type CardContentProps = {\n'
  + '  children: React.ReactNode;\n'
  + '};\n'
  + '\n'
  + 'const CardContent: FC<CardContentProps> = (props) => {\n'
  + '  const { children } = props;\n'
  + '\n'
  + '  return <div className={styles.cardContent}>{children}</div>;\n'
  + '};\n'
  + '\n'
  + 'CardContent.displayName = "Card.Content";\n'
  + '\n'
  + 'export { CardContent };\n'
  ;

sourceCode['card-content.module.scss'] = ''
  + '.cardContent {\n'
  + '  padding: 1rem;\n'
  + '}\n'
  ;

sourceCode['index.ts'] = ''
  + 'export { Card } from "./card";\n'
  ;

sourceCode['card-header.tsx'] = ''
  + 'import type { FC } from "react";\n'
  + '\n'
  + 'import styles from "./card-header.module.scss";\n'
  + '\n'
  + 'type CardHeaderProps = {\n'
  + '  children: React.ReactNode;\n'
  + '};\n'
  + '\n'
  + 'const CardHeader: FC<CardHeaderProps> = (props) => {\n'
  + '  const { children } = props;\n'
  + '\n'
  + '  return <div className={styles.cardHeader}>{children}</div>;\n'
  + '};\n'
  + '\n'
  + 'CardHeader.displayName = "Card.Header";\n'
  + '\n'
  + 'export { CardHeader };\n'
  ;

