// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode = ''
  + 'import type { CSSProperties } from "react";\n'
  + '\n'
  + 'type Style = CSSProperties & Record<`--${string}`, string>;\n'
  + '\n'
  + 'type UnresolvedStyle = {\n'
  + '  base: Style;\n'
  + '  variants: Record<string, Record<string, Style>>;\n'
  + '  cls: Record<string, string>;\n'
  + '};\n'
  + '\n'
  + 'export function resolveStyle(style: UnresolvedStyle): CSSProperties {\n'
  + '  const result = { ...style.base };\n'
  + '\n'
  + '  for (const clsVariant in style.cls) {\n'
  + '    const variantValue = style.cls[clsVariant];\n'
  + '    const variantStyles = style.variants[clsVariant][variantValue];\n'
  + '    Object.assign(result, variantStyles);\n'
  + '  }\n'
  + '\n'
  + '  return result;\n'
  + '}\n'
  ;

export default sourceCode;
