// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { DatePicker } from "@/components/DatePicker";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <DatePicker />;\n'
  + '}\n'
  ;

export default demoSourceCode;
