// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import type dayjs from "dayjs";\n'
  + 'import { useState } from "react";\n'
  + 'import { DatePicker } from "@/components/DatePicker";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const [date, setDate] = useState<dayjs.Dayjs | null>(null);\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem" alignItems="center">\n'
  + '      <DatePicker date={date} onDateChange={setDate} />\n'
  + '      <span>{date?.format("YYYY-MM-DD HH:mm:ss")}</span>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
