// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import type dayjs from "dayjs";\n'
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { Card } from "@/components/Card";\n'
  + 'import { useJss, useTheme } from "@/components/CopyUiProvider";\n'
  + 'import { DatePicker } from "@/components/DatePicker";\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const [date, setDate] = useState<dayjs.Dayjs | null>(null);\n'
  + '\n'
  + '  const jss = useJss();\n'
  + '  const theme = useTheme();\n'
  + '  const nothingStx = jss.hash({\n'
  + '    color: theme.colors.gray["600"],\n'
  + '    fontStyle: "italic",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" gap="1rem" alignItems="center">\n'
  + '      <DatePicker w="20rem" date={date} onDateChange={setDate} />\n'
  + '      <Card>\n'
  + '        <Card.Content>\n'
  + '          You selected:{" "}\n'
  + '          {date?.format("YYYY-MM-DD HH:mm:ss") ?? (\n'
  + '            <span className={nothingStx}>(nothing)</span>\n'
  + '          )}\n'
  + '        </Card.Content>\n'
  + '      </Card>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
