// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Background } from "@/components/Background";\n'
  + 'import { useJss } from "@/components/CopyUiProvider";\n'
  + 'import { Paper } from "@/components/Paper";\n'
  + 'import { lorem } from "./lorem";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const jss = useJss();\n'
  + '\n'
  + '  const stx = jss.hash({\n'
  + '    width: "30rem",\n'
  + '    height: "15rem",\n'
  + '  });\n'
  + '\n'
  + '  return (\n'
  + '    <Paper className={stx} withBorder radius="md">\n'
  + '      <Background.Container style={{ padding: "1rem" }}>\n'
  + '        <Background kind="dots" />\n'
  + '        <div style={{ position: "relative" }}>{lorem}</div>\n'
  + '      </Background.Container>\n'
  + '    </Paper>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
