// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Button } from "src/components/Button";\n'
  + 'import { Tooltip } from "src/components/Tooltip";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Tooltip\n'
  + '      anchor="pointer"\n'
  + '      placement="bottom-start"\n'
  + '      label="This is a tooltip"\n'
  + '      openDelay={750}\n'
  + '      triggerRender={({ onOpen, onClose }) => {\n'
  + '        return (\n'
  + '          <Button onMouseEnter={onOpen} onMouseLeave={onClose}>\n'
  + '            Hover me for a while\n'
  + '          </Button>\n'
  + '        );\n'
  + '      }}\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
