// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Button } from "src/components/Button";\n'
  + 'import { Tooltip } from "src/components/Tooltip";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Tooltip\n'
  + '      label="This is a tooltip"\n'
  + '      triggerRender={({ setRef, onOpen, onClose }) => (\n'
  + '        <Button ref={setRef} onMouseEnter={onOpen} onMouseLeave={onClose}>\n'
  + '          Hover me\n'
  + '        </Button>\n'
  + '      )}\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
