// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-09: Initial version.\n'
  + '- 2025-09-30: Support `className` prop for custom styling.\n'
  ;
