// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-09): Initial version.\n'
  + '- 0.1.1 (2025-09-30): Support `className` prop for custom styling.\n'
  + '- 0.1.2 (2025-10-10): Code formatting improvement.\n'
  + '- 0.1.3 (2025-11-23): Update the CSS variables names with camelCase.\n'
  ;
