// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Trash } from "lucide-react";\n'
  + '\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { IconButton } from "@/components/IconButton";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Flex gap="1rem" alignItems="center">\n'
  + '      <IconButton size="sm">\n'
  + '        <Trash size={"60%"} />\n'
  + '      </IconButton>\n'
  + '      <IconButton>\n'
  + '        <Trash size={"60%"} />\n'
  + '      </IconButton>\n'
  + '      <IconButton size="lg" variant="filled">\n'
  + '        <Trash size={"60%"} />\n'
  + '      </IconButton>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
