// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-23): Initial version.\n'
  + '- 0.1.1 (2025-10-03): Add `Avatar.Img` for image support. Update styles to\n'
  + '  ensure images fit within the avatar circle.\n'
  + '- 0.1.2 (2025-10-11): Using type `ColorName` for color prop.\n'
  + '- 0.1.3 (2025-10-21): Update avatar background color calculation for better\n'
  + '  contrast. And add a border.\n'
  + '- 0.1.4 (2025-11-18): Add `Avatar.Fallback` sub-component and support to show it\n'
  + '  when `Avatar.Img` not loaded.\n'
  + '- 0.1.5 (2025-11-19): Use `useRef` to hold the avatar store instance. Add make\n'
  + '  `Avatar` expose more props as a `span` element.\n'
  + '- 0.1.6 (2025-12-05): Add `variant` prop to `Avatar` component.\n'
  ;
