// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-23: Initial version.\n'
  + '- 2025-10-03: Add `Avatar.Img` for image support. Update styles to ensure images\n'
  + '  fit within the avatar circle.\n'
  + '- 2025-10-11: Using type `ColorName` for color prop.\n'
  + '- 2025-10-21: Update avatar background color calculation for better contrast.\n'
  + '  And add a border.\n'
  + '- 2025-11-18: Add `Avatar.Fallback` sub-component and support to show it when\n'
  + '  `Avatar.Img` not loaded.\n'
  ;
