// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-23: Initial version.\n'
  + '- 2025-10-03: Add `Avatar.Img` for image support. Update styles to ensure images\n'
  + '  fit within the avatar circle.\n'
  ;
