// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-05: Initial version.\n'
  + '- 2025-09-09: Extend DEFAULT_THEME with additional color palettes for red,\n'
  + '  green, and yellow.\n'
  + '- 2025-09-20: Add useTheme hook and refactor ThemeProvider to make it cleaner.\n'
  + '- 2025-09-23: Add tokens to the theme with prefix `inputBase` for input base\n'
  + '  components.\n'
  + '- 2025-09-29: Add tokens to the theme with prefix `inputBase` for size `xs` and\n'
  + '  `xl`.\n'
  + '- 2025-10-05: Extend DEFAULT_THEME with additional color palettes for pink,\n'
  + '  indigo, and purple. Update the `inputBaseBorderRadius` token. Code formatting\n'
  + '  improvement.\n'
  + '- 2025-10-08: Extend DEFAULT_THEME with additional color palettes for violet and\n'
  + '  indigo. Export the type `ColorNo` and `ColorName`.\n'
  + '- 2025-10-10: Update `inputBase{Xs,Sm,Md,Lg,Xl}FontSize` tokens to make them\n'
  + '  smaller.\n'
  ;
