// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-11-16): Initial version.\n'
  + '- 0.1.1 (2025-11-23): Refactor the code to use constants. Let the edges use\n'
  + '  bezier curves. Support dark mode.\n'
  + '- 0.1.2 (2025-12-07): Use Canvas API to measure text width to handle the node\n'
  + '  with long label.\n'
  + '- 0.1.3 (2025-12-13): Update to support the new color scheme.\n'
  ;
