// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['graph.tsx'] = ''
  + 'import type { FC } from "react";\n'
  + '\n'
  + 'type GraphNode = {\n'
  + '  id: string;\n'
  + '  label: string;\n'
  + '};\n'
  + '\n'
  + 'type GraphProps = {\n'
  + '  nodes: Array<GraphNode>;\n'
  + '};\n'
  + '\n'
  + 'const Graph: FC<GraphProps> = (props) => {\n'
  + '  return (\n'
  + '    <svg role="img" aria-label="graph" width="400" height="400">\n'
  + '      {props.nodes.map((node) => (\n'
  + '        <g key={node.id}>\n'
  + '          <circle cx={Math.random() * 400} cy={Math.random() * 400} r={20} />\n'
  + '          <text x={Math.random() * 400} y={Math.random() * 400}>\n'
  + '            {node.label}\n'
  + '          </text>\n'
  + '        </g>\n'
  + '      ))}\n'
  + '    </svg>\n'
  + '  );\n'
  + '};\n'
  + '\n'
  + 'export { Graph };\n'
  ;

sourceCode['index.ts'] = ''
  ;

