// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-30): Initial version.\n'
  + '- 0.1.1 (2025-10-04): Update code style.\n'
  + '- 0.1.2 (2025-10-25): Support `style` prop and add `Background.Container`\n'
  + '  sub-component.\n'
  + '- 0.1.3 (2025-11-05): Support the `chessboard` kind.\n'
  + '- 0.1.4 (2025-11-23): Support dark mode, and the `config` prop.\n'
  ;
