// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-10: Initial version.\n'
  + '- 2025-10-24: Support render code blocks (using internal rehype plugins). Wrap\n'
  + '  its children in `Typography.Root`.\n'
  ;
