// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-10): Initial version.\n'
  + '- 0.1.1 (2025-10-24): Support render code blocks (using internal rehype\n'
  + '  plugins). Wrap its children in `Typography.Root`.\n'
  + '- 0.1.2 (2025-11-16): Support render `strong`, `em`, `ol` elements by\n'
  + "  `Typography`'s sub-components. Use `Typography` instead of `Typography.Root`\n"
  + '  as the root component.\n'
  ;
