// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const sourceCode: Record<string, string> = {};

sourceCode['Markdown.tsx'] = ''
  + 'import type { FC } from "react";\n'
  + 'import ReactMarkdown from "react-markdown";\n'
  + '\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'type MarkdownProps = {\n'
  + '  children: string;\n'
  + '};\n'
  + '\n'
  + 'export const Markdown: FC<MarkdownProps> = (props) => {\n'
  + '  const { children } = props;\n'
  + '\n'
  + '  return (\n'
  + '    <ReactMarkdown\n'
  + '      components={{\n'
  + '        h1: Typography.H1,\n'
  + '        h2: Typography.H2,\n'
  + '        h3: Typography.H3,\n'
  + '        h4: Typography.H4,\n'
  + '        p: Typography.P,\n'
  + '        ul: Typography.Ul,\n'
  + '        li: Typography.Li,\n'
  + '        code: Typography.Code,\n'
  + '      }}\n'
  + '    >\n'
  + '      {children}\n'
  + '    </ReactMarkdown>\n'
  + '  );\n'
  + '};\n'
  ;

sourceCode['index.ts'] = ''
  + '// Markdown from copy-ui @ 2025-10-10.\n'
  + '\n'
  + 'export { Markdown } from "./Markdown";\n'
  ;

