// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-03): Initial version.\n'
  + '- 0.1.1 (2025-10-08): Update its `border-color` and `border-radius` styles.\n'
  + '- 0.1.2 (2025-11-01): Make it use `utils/jss` and put its styles in CSS layer,\n'
  + '  etc.\n'
  + '- 0.1.3 (2025-11-26): Support the month/year picker.\n'
  + '- 0.1.4 (2025-11-28): Optimize month/year picker scrolling by using state-driven\n'
  + '  styles and computing scroll distance from `event.deltaY`.\n'
  ;
