// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { Calendar } from "src/components/Calendar";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <div style={{ display: "flex", gap: "1rem", alignItems: "center" }}>\n'
  + '      <Calendar />\n'
  + '    </div>\n'
  + '  );\n'
  + '}\n'
  ;
