// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-17: Initial version.\n'
  + '- 2025-10-22: Add `withPadding` prop to control internal padding.\n'
  ;
