// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-17): Initial version.\n'
  + '- 0.1.1 (2025-10-22): Add `withPadding` prop to control internal padding.\n'
  + '- 0.1.2 (2025-10-25): Use `useJss` for styles & add `overflow: hidden` style.\n'
  + '- 0.1.3 (2025-11-23): Support dark mode.\n'
  ;
