// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-25: Initial version.\n'
  + '- 2025-09-30: Support `placement` prop for tooltip positioning.\n'
  + '- 2025-10-10: Move styles into `components` CSS layer. Code formatting\n'
  + '  improvement.\n'
  + '- 2025-10-31: Code formatting improvement.\n'
  + '- 2025-11-27: Support the `anchor` prop to make the tooltip follow the mouse\n'
  + '  cursor.\n'
  + '- 2025-12-14: Add `openDelay` prop to `Tooltip` to control the delay time before\n'
  + '  the tooltip is opened.\n'
  ;
