// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-25): Initial version.\n'
  + '- 0.1.1 (2025-09-30): Support `placement` prop for tooltip positioning.\n'
  + '- 0.1.2 (2025-10-10): Move styles into `components` CSS layer. Code formatting\n'
  + '  improvement.\n'
  + '- 0.1.3 (2025-10-31): Code formatting improvement.\n'
  + '- 0.1.4 (2025-11-27): Support the `anchor` prop to make the tooltip follow the\n'
  + '  mouse cursor.\n'
  + '- 0.1.5 (2025-12-14): Add `openDelay` prop to `Tooltip` to control the delay\n'
  + '  time before the tooltip is opened.\n'
  ;
