// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-25: Initial version.\n'
  + '- 2025-09-30: Support `placement` prop for tooltip positioning.\n'
  ;
