export const demoSourceCode = ''
  + 'import { Button } from "src/components/Button";\n'
  + 'import { Tooltip } from "src/components/Tooltip";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  return (\n'
  + '    <Tooltip\n'
  + '      label="This is a tooltip"\n'
  + '      triggerRender={({ setRef, onOpen, onClose }) => (\n'
  + '        <Button\n'
  + '          ref={setRef}\n'
  + '          onMouseEnter={onOpen}\n'
  + '          onMouseLeave={onClose}\n'
  + '        >\n'
  + '          Hover me\n'
  + '        </Button>\n'
  + '      )}\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;
