// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { Switch } from "@/components/Switch";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const [checked, setChecked] = useState(false);\n'
  + '\n'
  + '  return <Switch size="md" value={checked} onChange={setChecked} />;\n'
  + '}\n'
  ;

export default demoSourceCode;
