// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { Flex } from "@/components/Flex";\n'
  + 'import { Switch } from "@/components/Switch";\n'
  + 'import { Typography } from "@/components/Typography";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  const [checked, setChecked] = useState(false);\n'
  + '\n'
  + '  return (\n'
  + '    <Flex dir="column" items="center" gap="2rem">\n'
  + '      <Flex items="center" gap="0.25rem">\n'
  + '        <span>\n'
  + '          Use inline Switch with <Typography.Code>size="text"</Typography.Code>{" "}\n'
  + '          →\n'
  + '        </span>\n'
  + '        <Switch size="text" value={checked} onChange={setChecked} />\n'
  + '      </Flex>\n'
  + '      <Flex items="center" gap="1rem">\n'
  + '        <Switch size="xs" value={checked} onChange={setChecked} />\n'
  + '        <Switch size="sm" value={checked} onChange={setChecked} />\n'
  + '        <Switch size="md" value={checked} onChange={setChecked} />\n'
  + '        <Switch size="lg" value={checked} onChange={setChecked} />\n'
  + '        <Switch size="xl" value={checked} onChange={setChecked} />\n'
  + '      </Flex>\n'
  + '    </Flex>\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
