// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Graph } from "@/components/Graph/graph";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return <Graph nodes={[{ id: "foo", label: "Foo" }]} />;\n'
  + '}\n'
  ;

export default demoSourceCode;
