// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const demoSourceCode = ''
  + 'import { Graph } from "@/components/Graph/graph";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Graph\n'
  + '      nodes={[\n'
  + '        { id: "graph", label: "Graph" },\n'
  + '        { id: "copyuiprovider", label: "CopyUiProvider" },\n'
  + '        { id: "dagre", label: "@dagrejs/dagre", color: "green" },\n'
  + '      ]}\n'
  + '      edges={[\n'
  + '        { from: "graph", to: "dagre" },\n'
  + '        { from: "graph", to: "copyuiprovider" },\n'
  + '      ]}\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;

export default demoSourceCode;
