// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

const sourceCode: Record<string, string> = {};

sourceCode['index.tsx'] = ''
  + 'import { Graph } from "@/components/Graph/graph";\n'
  + '\n'
  + 'export default function Demo() {\n'
  + '  return (\n'
  + '    <Graph\n'
  + '      nodes={[\n'
  + '        { id: "graph", label: "Graph" },\n'
  + '        {\n'
  + '          id: "with-too-long-label",\n'
  + '          label:\n'
  + '            "This is a very long label -- it should be rendered correctly!",\n'
  + '        },\n'
  + '      ]}\n'
  + '      edges={[{ from: "graph", to: "with-too-long-label" }]}\n'
  + '    />\n'
  + '  );\n'
  + '}\n'
  ;
;

export default sourceCode;
