// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-10-04): Initial version.\n'
  + '- 0.1.1 (2025-10-05): Make the scrollbar appear on hover only.\n'
  + '- 0.1.2 (2025-10-10): Add a dragging state for the scrollbar thumb to prevent it\n'
  + '  from hiding while being dragged.\n'
  + '- 0.1.3 (2025-10-14): Update the style of the scrollbar thumb - make sure it has\n'
  + '  more alpha when dragging.\n'
  + '- 0.1.4 (2025-10-30): Add the variant `absolute` (it uses absolute positioning\n'
  + '  to make viewport just fill the container).\n'
  + '- 0.1.5 (2025-11-04): Support the `ScrollArea.ScrollbarWithThumb`.\n'
  + '- 0.1.6 (2025-12-11): Support the horizontal scrollbars with prop\n'
  + '  `orientation="horizontal"`.\n'
  + '- 0.1.7 (2026-02-14): Remove unnecessary `biome-ignore` around root hover\n'
  + '  handlers.\n'
  ;
