// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-10-04: Initial version.\n'
  + '- 2025-10-05: Make the scrollbar appear on hover only.\n'
  ;
