// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 0.1.0 (2025-09-11): Initial version.\n'
  + '- 0.1.1 (2025-09-25): Improved TimeSelector styles for better appearance.\n'
  + "- 0.1.2 (2025-09-25): Use `onToggle` instead of `onClick` in `Popover.Trigger`'s\n"
  + '  render prop.\n'
  + '- 0.1.3 (2025-10-04): Replace preset list with ScrollArea component. Add proper\n'
  + '  form labels with `htmlFor` attributes. Extract preset data to array. Update\n'
  + '  button styles and cancel button variant. Code formatting improvements.\n'
  + '- 0.1.4 (2025-11-06): Refactor code and use `Field` component for input fields.\n'
  + '  Adjust input widths and spacing, etc.\n'
  + '- 0.1.5 (2025-11-28): Support parsing the "from" and "to" fields to the AST.\n'
  + '  Support the timezone selection, support the `safeResolveTimeRange` function --\n'
  + '  help user to resolve the time range to the real time range.\n'
  ;
