// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-11: Initial version.\n'
  + '- 2025-09-25: Improved TimeSelector styles for better appearance.\n'
  + "- 2025-09-25: Use `onToggle` instead of `onClick` in `Popover.Trigger`'s render\n"
  + '  prop.\n'
  + '- 2025-10-04: Replace preset list with ScrollArea component. Add proper form\n'
  + '  labels with `htmlFor` attributes. Extract preset data to array. Update button\n'
  + '  styles and cancel button variant. Code formatting improvements.\n'
  + '- 2025-11-06: Refactor code and use `Field` component for input fields. Adjust\n'
  + '  input widths and spacing, etc.\n'
  + '- 2025-11-28: Support parsing the "from" and "to" fields to the AST. Support the\n'
  + '  timezone selection, support the `safeResolveTimeRange` function -- help user\n'
  + '  to resolve the time range to the real time range.\n'
  ;
