// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const changelog = ''
  + '- 2025-09-11: Initial version.\n'
  + '- 2025-09-25: Improved TimeSelector styles for better appearance.\n'
  + "- 2025-09-25: Use `onToggle` instead of `onClick` in `Popover.Trigger`'s render\n"
  + '  prop.\n'
  ;
