// This file is auto-generated by `just codegen`.
// Do not edit this file directly.

export const demoSourceCode = ''
  + 'import { useState } from "react";\n'
  + '\n'
  + 'import { TimeSelector, type TimeRange } from "src/components/TimeSelector";\n'
  + '\n'
  + 'export function Demo() {\n'
  + '  const [timeRange, setTimeRange] = useState<TimeRange | undefined>(undefined);\n'
  + '\n'
  + '  return <TimeSelector value={timeRange} onChange={setTimeRange} />;\n'
  + '}\n'
  ;
