export const sourceCode: Record<string, string> = {};

sourceCode['TimeSelector.tsx'] = ''
  + 'import { useContext, useLayoutEffect, useMemo, useRef, useState, type CSSProperties, type FC } from "react";\n'
  + 'import { Clock } from "lucide-react";\n'
  + '\n'
  + 'import { Button } from "../Button";\n'
  + 'import { Popover } from "../Popover";\n'
  + 'import { ThemeContext } from "../ThemeProvider";\n'
  + '\n'
  + 'import styles from "./TimeSelector.module.scss";\n'
  + 'import { Input } from "../Input";\n'
  + '\n'
  + 'export type TimeRange = {\n'
  + '  from: string;\n'
  + '  to: string;\n'
  + '}\n'
  + '\n'
  + 'export type TimeSelectorProps = {\n'
  + '  value?: TimeRange;\n'
  + '  onChange?: (value: TimeRange) => void;\n'
  + '};\n'
  + '\n'
  + 'export const TimeSelector: FC<TimeSelectorProps> = (props) => {\n'
  + '  const {\n'
  + '    value,\n'
  + '    onChange,\n'
  + '  } = props;\n'
  + '\n'
  + '  const showTitle = useMemo(() => {\n'
  + '    if (value) {\n'
  + "      if (value.to === 'now' && /now - \\d+(m|h|d|y)/.test(value.from)) {\n"
  + '        let regex = /now - (\\d+)(m|h|d|y)/;\n'
  + '        let match = value.from.match(regex);\n'
  + '        if (match) {\n'
  + '          let amount = match[1];\n'
  + '          let unit = match[2];\n'
  + "          let unitFull = '';\n"
  + '          switch (unit) {\n'
  + "            case 'm':\n"
  + "              unitFull = amount === '1' ? 'minute' : 'minutes';\n"
  + '              break;\n'
  + "            case 'h':\n"
  + "              unitFull = amount === '1' ? 'hour' : 'hours';\n"
  + '              break;\n'
  + "            case 'd':\n"
  + "              unitFull = amount === '1' ? 'day' : 'days';\n"
  + '              break;\n'
  + "            case 'y':\n"
  + "              unitFull = amount === '1' ? 'year' : 'years';\n"
  + '              break;\n'
  + '          }\n'
  + '          return `Last ${amount} ${unitFull}`;\n'
  + '        } else {\n'
  + "          throw new Error('Invalid time range format');\n"
  + '        }\n'
  + '      }\n'
  + '    }\n'
  + "    return 'Select Time';\n"
  + '  }, [value]);\n'
  + '\n'
  + '  return (\n'
  + '    <Popover>\n'
  + '      <Popover.Trigger\n'
  + '        render={({ setRef, onClick }) => (\n'
  + '          <Button\n'
  + '            ref={(el) => { el && setRef(el); return; }}\n'
  + "            leftSection={<Clock size='1.25rem' />}\n"
  + '            onClick={onClick}\n'
  + '          >\n'
  + '            <span>{showTitle}</span>\n'
  + '          </Button>\n'
  + '        )}\n'
  + '      />\n'
  + '      <Popover.Portal\n'
  + '        onClickOutside={({ closePortal }) => closePortal()}\n'
  + '        render={({ setRef, togglePortal, isOpen, floatingStyles }) => (\n'
  + '          isOpen && (\n'
  + '            <TimeSelectorPortal\n'
  + '              setRef={setRef}\n'
  + '              togglePortal={togglePortal}\n'
  + '              floatingStyles={floatingStyles}\n'
  + '              value={value}\n'
  + '              onChange={(v) => { onChange?.(v); togglePortal() }}\n'
  + '            />\n'
  + '          )\n'
  + '        )}\n'
  + '      />\n'
  + '    </Popover>\n'
  + '  );\n'
  + '}\n'
  + '\n'
  + "TimeSelector.displayName = 'TimeSelector';\n"
  + '\n'
  + 'interface TimeSelectorPortalProps {\n'
  + '  setRef: (el: HTMLElement) => void;\n'
  + '  togglePortal: () => void;\n'
  + '  floatingStyles: CSSProperties;\n'
  + '\n'
  + '  value?: TimeRange;\n'
  + '  onChange?: (value: TimeRange) => void;\n'
  + '}\n'
  + '\n'
  + 'const TimeSelectorPortal: FC<TimeSelectorPortalProps> = (props) => {\n'
  + '  const {\n'
  + '    setRef,\n'
  + '    togglePortal,\n'
  + '    floatingStyles,\n'
  + '\n'
  + '    value,\n'
  + '    onChange,\n'
  + '  } = props;\n'
  + '\n'
  + '  const theme = useContext(ThemeContext);\n'
  + '\n'
  + '  const detailRef = useRef<HTMLDivElement | null>(null);\n'
  + '\n'
  + '  const [detailHeight, setDetailHeight] = useState<number | null>(null);\n'
  + "  const [valueFrom, setValueFrom] = useState(value?.from || '');\n"
  + "  const [valueTo, setValueTo] = useState(value?.to || '');\n"
  + '\n'
  + '  const computedStyle = {\n'
  + "    '--color-border': theme.colors.gray['100'],\n"
  + "    '--radius': '0.375rem',\n"
  + "    '--preset-list-height': detailHeight ? `${detailHeight}px` : '0px',\n"
  + "    '--color-hover': theme.colors.gray['000'],\n"
  + '  };\n'
  + '\n'
  + '  useLayoutEffect(() => {\n'
  + '    const detail = detailRef.current;\n'
  + '    if (detail) {\n'
  + '      setDetailHeight(detail.clientHeight);\n'
  + '    }\n'
  + '  }, []);\n'
  + '\n'
  + '  return (\n'
  + '    <div\n'
  + '      ref={(el) => setRef(el!)}\n'
  + '      className={styles.portal}\n'
  + '      style={{\n'
  + '        ...computedStyle,\n'
  + '        ...floatingStyles,\n'
  + '      }}\n'
  + '    >\n'
  + '      <div className={styles.detail} ref={detailRef}>\n'
  + '        <div className={styles.inputField}>\n'
  + '          <label>From</label>\n'
  + '          <Input\n'
  + '            value={valueFrom}\n'
  + "            style={{ width: '18rem' }}\n"
  + '            onChange={(e) => setValueFrom(e.target.value)}\n'
  + '            placeholder=\'The start time, e.g. "now - 15m"\'\n'
  + '          />\n'
  + '        </div>\n'
  + '        <div className={styles.inputField}>\n'
  + '          <label>To</label>\n'
  + '          <Input\n'
  + '            value={valueTo}\n'
  + "            style={{ width: '18rem' }}\n"
  + '            onChange={(e) => setValueTo(e.target.value)}\n'
  + '            placeholder=\'The end time, e.g. "now"\'\n'
  + '          />\n'
  + '        </div>\n'
  + '        <div className={styles.detailFooter}>\n'
  + '          <Button\n'
  + '            size="sm"\n'
  + '            variant="filled"\n'
  + '            onClick={() => onChange?.({ from: valueFrom, to: valueTo })}\n'
  + '          >\n'
  + '            Apply\n'
  + '          </Button>\n'
  + '          <Button \n'
  + '            size="sm"\n'
  + '            variant="default"\n'
  + '            onClick={() => togglePortal()}\n'
  + '          >\n'
  + '            Cancel\n'
  + '          </Button>\n'
  + '        </div>\n'
  + '      </div>\n'
  + '      <menu className={styles.presetList}>\n'
  + "        <li onClick={() => onChange?.({ from: 'now - 5m', to: 'now' })}>Last 5 minutes</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 15m', to: 'now' })}>Last 15 minutes</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 30m', to: 'now' })}>Last 30 minutes</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 1h', to: 'now' })}>Last 1 hour</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 3h', to: 'now' })}>Last 3 hours</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 6h', to: 'now' })}>Last 6 hours</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 12h', to: 'now' })}>Last 12 hours</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 24h', to: 'now' })}>Last 24 hours</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 2d', to: 'now' })}>Last 2 days</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 7d', to: 'now' })}>Last 7 days</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 30d', to: 'now' })}>Last 30 days</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 90d', to: 'now' })}>Last 90 days</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 180d', to: 'now' })}>Last 180 days</li>\n"
  + "        <li onClick={() => onChange?.({ from: 'now - 1y', to: 'now' })}>Last 1 year</li>\n"
  + '      </menu>\n'
  + '    </div>\n'
  + '  )\n'
  + '}\n'
  + '\n'
  + "TimeSelectorPortal.displayName = 'TimeSelector.Portal';\n"
  ;

sourceCode['TimeSelector.module.scss'] = ''
  + '.portal {\n'
  + '  display: flex;\n'
  + '  flex-direction: row;\n'
  + '\n'
  + '  background-color: white;\n'
  + '  border: 1px solid var(--color-border);\n'
  + '  border-radius: var(--radius);\n'
  + '}\n'
  + '\n'
  + '.detail {\n'
  + '  display: flex;\n'
  + '  flex-direction: column;\n'
  + '  gap: 0.75rem;\n'
  + '\n'
  + '  padding: 0.75rem;\n'
  + '  border-right: 1px solid var(--color-border);\n'
  + '}\n'
  + '\n'
  + '.detailFooter {\n'
  + '  display: flex;\n'
  + '  justify-content: flex-start;\n'
  + '  gap: 0.5rem;\n'
  + '  margin-top: 2rem;\n'
  + '}\n'
  + '\n'
  + '.inputField {\n'
  + '  display: flex;\n'
  + '  flex-direction: column;\n'
  + '  gap: 0.125rem;\n'
  + '\n'
  + '  label {\n'
  + '    font-size: 0.875rem;\n'
  + '  }\n'
  + '}\n'
  + '\n'
  + '.presetList {\n'
  + '  display: flex;\n'
  + '  flex-direction: column;\n'
  + '  gap: 0.125rem;\n'
  + '  padding: 0.5rem;\n'
  + '\n'
  + '  width: 12rem;\n'
  + '  height: var(--preset-list-height);\n'
  + '\n'
  + '  overflow: auto;\n'
  + '\n'
  + '  li {\n'
  + '    padding: 0.25rem 0.5rem;\n'
  + '    border-radius: var(--radius);\n'
  + '\n'
  + '    cursor: pointer;\n'
  + '\n'
  + '    &:hover {\n'
  + '      background-color: var(--color-hover);\n'
  + '    }\n'
  + '  }\n'
  + '}\n'
  ;

sourceCode['index.ts'] = ''
  + '// TimeSelector from copy-ui @ 2025-09-25.\n'
  + '\n'
  + "export { TimeSelector } from './TimeSelector';\n"
  + "export type { TimeRange } from './TimeSelector';\n"
  ;

